#!/usr/bin/env python3
"""Build the api-client-python GitBook space.

This orchestrator wraps Sphinx so that the MyST-Markdown + RST sources in
``submodules/api-client-python/docs/source`` are rendered to GitBook-native
Markdown under ``spaces/api-client-python/docs``.

Every file under ``spaces/api-client-python/docs`` (except the static
``.gitbook.yaml``) is regenerated by this script:

* ``SUMMARY.md`` is composed from ``SUMMARY_CONFIG`` so the sidebar always
  matches the set of pages the build emits.
* The page tree under ``reference/``, ``user-guide/`` and ``releases/`` is
  produced by Sphinx + sphinx-apidoc + the upstream ``_generate_groups.py``.
* ``.gitbook/assets/`` is wiped and re-populated from the submodule's
  ``_static/images/`` directory.

This means a full rebuild is byte-for-byte reproducible from the submodule
SHA pinned in ``submodules/api-client-python``: running
``scripts/build_api_client_python_docs.py --check`` re-runs the whole
pipeline into a scratch directory and exits non-zero if anything differs
from what is committed under ``spaces/api-client-python/docs``.

The pipeline itself works as follows. It deliberately leaves the submodule
untouched and instead:

1. Stages the submodule's ``docs/source`` tree into ``.docs-build/source``.
2. Runs the submodule's ``_generate_groups.py`` to (re)create the per-endpoint
   reference pages, with its module-level ``REPO_ROOT`` and ``OUTPUT_DIR``
   monkey-patched to the staged paths so nothing is written into the submodule
   working tree.
3. Drops in an overlay ``conf.py`` that re-exports the submodule conf and
   appends ``sphinx_markdown_builder`` to ``extensions``.
4. Invokes ``sphinx-build -b markdown`` against the staged source.
5. Post-processes the generated Markdown:
   - rewrites ``.html`` links to ``.md``
   - strips residual ``{toctree}`` and ``{eval-rst}`` fences
   - converts ``{grid-item-card}`` blocks to GitBook-friendly bullet lists
   - rewrites ``_static/images/...`` references to ``.gitbook/assets/...``
   - copies image assets into ``<output>/.gitbook/assets``
6. Writes ``<output>/SUMMARY.md`` from ``SUMMARY_CONFIG``.
"""

from __future__ import annotations

import argparse
import filecmp
import importlib.util
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable, List, Optional, Tuple


REPO_ROOT = Path(__file__).resolve().parents[1]
SUBMODULE_ROOT = REPO_ROOT / "submodules" / "api-client-python"
SUBMODULE_DOCS_SOURCE = SUBMODULE_ROOT / "docs" / "source"
SUBMODULE_CHANGELOG = SUBMODULE_ROOT / "CHANGELOG.md"
SUBMODULE_OPENAPI = SUBMODULE_ROOT / "openapi.yaml"

STAGING_ROOT = REPO_ROOT / ".docs-build" / "api-client-python"
STAGED_SOURCE = STAGING_ROOT / "source"
STAGED_BUILD = STAGING_ROOT / "build"
CHECK_OUTPUT = STAGING_ROOT / "check-output"

DEFAULT_OUTPUT_ROOT = REPO_ROOT / "spaces" / "api-client-python" / "docs"
GITBOOK_ASSETS_REL = Path(".gitbook") / "assets"

# Files in the output root that are committed by hand and must survive a
# clean rebuild. Everything else under the output root (including
# SUMMARY.md and .gitbook/assets/) is owned by this script.
PRESERVED_PATHS = {
    ".gitbook.yaml",
}

# Maps an openapi.yaml ``tags[].name`` value to the slug we use for the
# corresponding GitBook section. Multiple openapi tags can collapse onto a
# single slug (the Python client lumps the deprecation-free v2 endpoints
# together with their "full catalog" / "stream" siblings).
_OPENAPI_TAG_TO_SLUG = {
    "Reference Data": ("reference-data", "Reference Data"),
    "Catalog v2": ("catalog-v2", "Catalog V2"),
    "Full catalog v2": ("catalog-v2", "Catalog V2"),
    "Timeseries": ("timeseries", "Timeseries"),
    "Timeseries stream": ("timeseries", "Timeseries"),
    "Taxonomy": ("taxonomy", "Taxonomy"),
    "Taxonomy Metadata": ("taxonomy", "Taxonomy"),
    "Profile": ("asset-profiles", "Asset Profiles"),
    "List of blockchain entities v2": ("blockchain-data", "Blockchain Data"),
    "Full blockchain entities v2": ("blockchain-data", "Blockchain Data"),
    "Security Master": ("security-master", "Security Master"),
    "Constituent Snapshots": ("constituents", "Constituents"),
    "Constituent Timeframes": ("constituents", "Constituents"),
    "Blockchain Metadata": ("blockchain-metadata", "Blockchain Metadata"),
}

# Fallback ordering used if openapi.yaml is missing or unreadable. Mirrors
# the openapi tag order at the time of writing.
_FALLBACK_GROUP_PAGES: List[Tuple[str, str]] = [
    ("reference-data", "Reference Data"),
    ("catalog-v2", "Catalog V2"),
    ("timeseries", "Timeseries"),
    ("taxonomy", "Taxonomy"),
    ("asset-profiles", "Asset Profiles"),
    ("blockchain-data", "Blockchain Data"),
    ("security-master", "Security Master"),
    ("constituents", "Constituents"),
    ("blockchain-metadata", "Blockchain Metadata"),
]


def _compute_group_pages() -> List[Tuple[str, str]]:
    """Return ``(slug, label)`` pairs in the order they appear in openapi.yaml.

    The openapi spec ships in the submodule and is the canonical ordering
    of endpoint tags for the public REST API. Aligning the GitBook sidebar
    to it keeps the Python-client docs and the OpenAPI / Redoc reference
    in lockstep.
    """
    if not SUBMODULE_OPENAPI.is_file():
        return list(_FALLBACK_GROUP_PAGES)
    try:
        text = SUBMODULE_OPENAPI.read_text()
    except OSError:
        return list(_FALLBACK_GROUP_PAGES)

    ordered: List[Tuple[str, str]] = []
    seen: set[str] = set()
    # Match top-level ``tags:`` entries -- two-space indent, ``- name: <Tag>``.
    for match in re.finditer(r"^\s+-\s+name:\s+(.+?)\s*$", text, re.MULTILINE):
        slug_label = _OPENAPI_TAG_TO_SLUG.get(match.group(1).strip())
        if slug_label is None or slug_label[0] in seen:
            continue
        ordered.append(slug_label)
        seen.add(slug_label[0])
    return ordered or list(_FALLBACK_GROUP_PAGES)


GROUP_PAGES: List[Tuple[str, str]] = _compute_group_pages()


# Mapping ``slug -> ordered list of method names`` populated by
# ``regenerate_group_pages`` after _generate_groups.py has classified
# every public method on ``CoinMetricsClient``. Used by ``_render_summary``
# to nest every endpoint method under its parent group in the GitBook
# sidebar, and by ``_write_group_index_pages`` to render per-group
# README.md landing pages.
GROUP_METHODS: dict[str, List[str]] = {}

# Per-class slugs that follow the same per-method-page model as the
# CoinMetricsClient endpoint groups: each method gets its own
# ``reference/<slug>/<method>.md`` page, and ``reference/<slug>/README.md``
# is a curated landing page that lists the methods. See
# ``regenerate_class_pages``.
#
# Each entry is ``(slug, label, module_path, class_name)``. The module is
# imported with ``importlib`` so the script must be run inside an
# environment where the api-client-python package is importable (the build
# venv installs it via ``pip install -e submodules/api-client-python``).
EXTRA_CLASS_PAGES: List[Tuple[str, str, str, str]] = [
    ("data-collection", "DataCollection", "coinmetrics._data_collection", "DataCollection"),
    ("parallel-data-collection", "ParallelDataCollection", "coinmetrics._data_collection", "ParallelDataCollection"),
    ("cm-stream", "CmStream", "coinmetrics.api_client", "CmStream"),
]

# Populated by ``regenerate_class_pages`` -- ``slug -> [method, ...]``.
EXTRA_CLASS_METHODS: dict[str, List[str]] = {}

# Per-class metadata so post-processing can look up the fully-qualified
# class path for anchor generation. Mirrors EXTRA_CLASS_PAGES at runtime.
EXTRA_CLASS_QUALIFIERS: dict[str, str] = {}

# Slug + label for the auto-generated Exceptions section. Each exception
# class in ``coinmetrics._exceptions`` becomes its own page.
EXCEPTIONS_SLUG = "exceptions"
EXCEPTIONS_LABEL = "Exceptions"
EXCEPTIONS_MODULE = "coinmetrics._exceptions"

# Populated by ``regenerate_exception_pages`` -- ordered list of class names.
EXCEPTION_CLASSES: List[str] = []

# Source-relative path -> output-relative path. Pages not listed are emitted
# at the same relative location (with name normalisation underscore->dash).
PAGE_RENAMES = {
    "index.md": "README.md",
    "user-guide/index.md": "user-guide/README.md",
    "reference/api_client.md": "reference/README.md",
    "reference/coinmetricsclient.md": "reference/coinmetricsclient.md",
    "releases/changelog.md": "releases/changelog.md",
}

# Generated per-group landing pages live under
# ``reference/coinmetricsclient/<slug>/README.md``; the actual per-method
# pages are mapped wholesale by ``collect_outputs`` (see the
# ``reference/groups/`` -> ``reference/coinmetricsclient/`` substitution
# there).
for slug, _label in GROUP_PAGES:
    PAGE_RENAMES[f"reference/groups/{slug}/index.md"] = (
        f"reference/coinmetricsclient/{slug}/README.md"
    )

# Per-class index pages (DataCollection, ParallelDataCollection, CmStream)
# are produced by ``regenerate_class_pages`` as ``<slug>/index.md``; route
# them to ``<slug>/README.md`` so GitBook treats them as the section
# landing page.
for _slug, _label, _module, _class_name in EXTRA_CLASS_PAGES:
    PAGE_RENAMES[f"reference/{_slug}/index.md"] = (
        f"reference/{_slug}/README.md"
    )

# Same routing for the auto-generated Exceptions index.
PAGE_RENAMES[f"reference/{EXCEPTIONS_SLUG}/index.md"] = (
    f"reference/{EXCEPTIONS_SLUG}/README.md"
)

# Output-relative path -> H1 title. Used by post-processing to replace the
# default ``coinmetrics.<module> module`` heading sphinx-apidoc emits with a
# friendlier label that matches the upstream curated pages.
PAGE_TITLES = {
    "reference/exceptions.md": "Exceptions",
}

# Default class qualifier used to resolve "plain" autodoc method headings
# (the ones rendered as ``ClassName.method(...)`` without a module prefix,
# typically emitted by ``.. automethod::`` under a ``.. currentmodule::``
# directive). The qualifier is the fully-qualified class name; method
# anchors are built as ``<qualifier>.<method>``.
#
# Pages without an entry rely on the most-recent ``*class*`` / ``*exception*``
# heading on the page to set the qualifier dynamically.
PAGE_DEFAULT_CLASS_QUALIFIER = {
    # Per-method pages live under reference/coinmetricsclient/<slug>/ and
    # contain a single ``CoinMetricsClient.<method>`` automethod block.
    "reference/coinmetricsclient/": "coinmetrics.api_client.CoinMetricsClient",
}

# Populate qualifiers for the additional per-class sections so per-method
# pages under reference/<slug>/ can resolve their anchor IDs without an
# explicit ``*class*`` heading.
for _slug, _label, _module, _class_name in EXTRA_CLASS_PAGES:
    PAGE_DEFAULT_CLASS_QUALIFIER[f"reference/{_slug}/"] = (
        f"{_module}.{_class_name}"
    )

# Curated upstream reference pages we discard during staging because the
# scaffolded per-method pages produced by ``regenerate_class_pages`` /
# ``regenerate_exception_pages`` replace them entirely.
DROP_FROM_STAGED_REFERENCE = (
    "exceptions.md",
    "data_collection.md",
    "parallel_data_collection.md",
    "cm_stream.md",
)

# sphinx-apidoc is no longer required: every class we want to document
# (CoinMetricsClient, DataCollection, ParallelDataCollection, CmStream and
# the exception hierarchy) is scaffolded explicitly so each method / class
# gets its own page. Keeping the constant for backwards-compatibility but
# leaving the apidoc step disabled in ``stage_source``.
APIDOC_EXCLUDE_FILES: Tuple[str, ...] = ()


# ---------------------------------------------------------------------------
# SUMMARY.md generation
# ---------------------------------------------------------------------------


# Declarative GitBook navigation. Each section is a (heading_or_None, entries)
# pair, where ``entries`` is an ordered list of ``(title, target, children)``
# triples. ``target`` is the link target relative to the GitBook space root.
# ``children`` is itself a list of ``(title, target, [])`` triples (only one
# nesting level is supported, which matches the upstream pydata layout).
#
# The CoinMetricsClient entry's children are filled in from ``GROUP_PAGES``
# at render time so the sidebar always lists every group page the build
# emits under ``reference/coinmetricsclient/``.
SUMMARY_INTRO = ("Getting Started", "README.md")


def _render_summary() -> str:
    """Compose ``SUMMARY.md`` from the per-section state populated by the
    build (``GROUP_PAGES``, ``GROUP_METHODS``, ``EXTRA_CLASS_METHODS``,
    ``EXCEPTION_CLASSES``).

    The Reference section nests every class under its landing page and
    every method under its parent class, mirroring the on-page heading
    hierarchy so GitBook search / sidebar surface every documented symbol.
    """
    lines: List[str] = ["# Table of contents", ""]
    intro_title, intro_target = SUMMARY_INTRO
    lines.append(f"* [{intro_title}]({intro_target})")
    lines.append("")

    # User Guide
    lines.append("## User Guide")
    lines.append("")
    lines.append("* [Overview](user-guide/README.md)")
    lines.append("* [Core Concepts](user-guide/core-concepts.md)")
    lines.append("* [Best Practices](user-guide/best-practices.md)")
    lines.append("* [Troubleshooting](user-guide/troubleshooting.md)")
    lines.append("")

    # Reference
    lines.append("## Reference")
    lines.append("")
    lines.append("* [Overview](reference/README.md)")

    # CoinMetricsClient: nested by openapi-yaml group and per-method.
    # API symbol names (class.method, exception classes) are wrapped in
    # backticks so GitBook renders them in monospace in the sidebar,
    # matching the in-page H1 styling and the pydata-sphinx-theme look.
    lines.append("* [`CoinMetricsClient`](reference/coinmetricsclient.md)")
    for slug, label in GROUP_PAGES:
        base = f"reference/coinmetricsclient/{slug}"
        lines.append(f"  * [{label}]({base}/README.md)")
        for method_name in GROUP_METHODS.get(slug, []):
            method_title = f"`CoinMetricsClient.{method_name}`"
            lines.append(f"    * [{method_title}]({base}/{method_name}.md)")

    # DataCollection / ParallelDataCollection / CmStream: each is a class
    # with one page per method nested underneath.
    for slug, label, _module, class_name in EXTRA_CLASS_PAGES:
        base = f"reference/{slug}"
        lines.append(f"* [{label}]({base}/README.md)")
        for method_name in EXTRA_CLASS_METHODS.get(slug, []):
            method_title = f"`{class_name}.{method_name}`"
            lines.append(f"  * [{method_title}]({base}/{method_name}.md)")

    # Exceptions: one page per exception class.
    base = f"reference/{EXCEPTIONS_SLUG}"
    lines.append(f"* [{EXCEPTIONS_LABEL}]({base}/README.md)")
    for cls_name in EXCEPTION_CLASSES:
        lines.append(f"  * [`{cls_name}`]({base}/{cls_name}.md)")
    lines.append("")

    # Releases
    lines.append("## RELEASES")
    lines.append("")
    lines.append("* [Changelog](releases/changelog.md)")
    return "\n".join(lines).rstrip() + "\n"


def write_summary(output_root: Path) -> None:
    """Write the rendered ``SUMMARY.md`` into ``output_root``."""
    (output_root / "SUMMARY.md").write_text(_render_summary())


# ---------------------------------------------------------------------------
# Staging
# ---------------------------------------------------------------------------


def _wipe(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)


def stage_source() -> None:
    """Copy the submodule docs source into the staging root."""
    if not SUBMODULE_DOCS_SOURCE.is_dir():
        raise SystemExit(
            f"Cannot find submodule docs source at {SUBMODULE_DOCS_SOURCE}. "
            "Did you run `git submodule update --init --recursive`?"
        )
    _wipe(STAGING_ROOT)
    STAGING_ROOT.mkdir(parents=True)
    shutil.copytree(SUBMODULE_DOCS_SOURCE, STAGED_SOURCE)

    # Bring in the CHANGELOG so the toctree entry "releases/CHANGELOG"
    # resolves. The Sphinx myst-parser does not need a file extension on
    # toctree references, so we expose the changelog at releases/changelog.md
    # and patch the toctree below.
    releases_dir = STAGED_SOURCE / "releases"
    releases_dir.mkdir(exist_ok=True)
    if SUBMODULE_CHANGELOG.is_file():
        shutil.copy2(SUBMODULE_CHANGELOG, releases_dir / "changelog.md")

    _patch_index_toctree(STAGED_SOURCE / "index.md")
    _drop_curated_reference_pages(STAGED_SOURCE / "reference")
    _strip_grids_in_tree(STAGED_SOURCE)
    _strip_toctrees_in_tree(STAGED_SOURCE)
    _convert_admonitions_in_tree(STAGED_SOURCE)
    _write_overlay_conf(STAGED_SOURCE / "conf.py")


def _drop_curated_reference_pages(reference_dir: Path) -> None:
    """Remove staged curated pages that sphinx-apidoc will replace."""
    for name in DROP_FROM_STAGED_REFERENCE:
        target = reference_dir / name
        if target.exists():
            target.unlink()


def _run_apidoc(package_dir: Path, output_dir: Path) -> None:
    """Run ``sphinx-apidoc`` to scaffold per-module reference pages.

    The generated ``coinmetrics.<module>.rst`` files use the standard
    ``automodule :members: :undoc-members: :show-inheritance:`` template
    that produces the canonical Sphinx API-reference look.

    Two upstream knobs need taming:

    * ``-P`` (private) is required so ``coinmetrics._data_collection`` and
      ``coinmetrics._exceptions`` (both underscore-prefixed at the module
      level) are emitted, but it also injects ``:private-members:`` into
      every directive. We strip that line so single-leading-underscore
      *attributes* inside the modules stay hidden.
    * ``-T`` skips the ``modules.rst`` table-of-contents file (we drive
      navigation from SUMMARY.md instead). We also remove the package-level
      ``coinmetrics.rst`` for the same reason.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    excludes = [str(package_dir / name) for name in APIDOC_EXCLUDE_FILES]
    cmd = [
        sys.executable,
        "-m",
        "sphinx.ext.apidoc",
        "-e",      # one file per module
        "-M",      # module docs above submodule entries
        "-T",      # do not emit the modules.rst TOC
        "-P",      # include underscore-prefixed modules
        "-f",      # overwrite existing files
        "-o",
        str(output_dir),
        str(package_dir),
        *excludes,
    ]
    print("$ " + " ".join(cmd))
    result = subprocess.run(cmd, cwd=str(REPO_ROOT))
    if result.returncode != 0:
        # Older sphinx releases ship apidoc only as a console script rather
        # than as a runnable module; fall back to the CLI before giving up.
        result = subprocess.run(
            ["sphinx-apidoc", *cmd[3:]],
            cwd=str(REPO_ROOT),
        )
        if result.returncode != 0:
            raise SystemExit(f"sphinx-apidoc exited with {result.returncode}")

    # Drop the package-level "coinmetrics" landing page; SUMMARY.md provides
    # navigation, and the page would otherwise emit an empty automodule
    # block plus a redundant submodule toctree.
    package_index = output_dir / f"{package_dir.name}.rst"
    if package_index.exists():
        package_index.unlink()

    # Strip ``:private-members:`` from every generated directive so we only
    # document the public surface of each module.
    for rst in output_dir.glob(f"{package_dir.name}.*.rst"):
        text = rst.read_text()
        text = re.sub(r"^\s*:private-members:\s*\n", "", text, flags=re.MULTILINE)
        rst.write_text(text)


def _patch_index_toctree(index_path: Path) -> None:
    """Point the landing toctree at the staged ``releases/changelog`` page."""
    text = index_path.read_text()
    text = text.replace("releases/CHANGELOG", "releases/changelog")
    index_path.write_text(text)


# Matches a sphinx-design ``::::{grid}`` block (4 colons) wrapping one or
# more ``:::{grid-item-card}`` (3 colons) entries. The grid is rendered by
# pydata-sphinx-theme as visual landing cards, but in GitBook it would just
# duplicate the navigation already shown in the left sidebar (see
# SUMMARY.md), so we drop the entire block at the source-text level before
# Sphinx parses it.
_GRID_BLOCK_RE = re.compile(
    r"\n?^::::\{grid\}[^\n]*\n.*?^::::\s*$",
    re.DOTALL | re.MULTILINE,
)


def _strip_grids_in_tree(root: Path) -> None:
    """Remove every ``{grid}`` block from Markdown files under ``root``."""
    for md in root.rglob("*.md"):
        text = md.read_text()
        new_text = _GRID_BLOCK_RE.sub("", text)
        if new_text != text:
            md.write_text(new_text)


# Matches a MyST ``{toctree}`` directive. ``sphinx_markdown_builder`` lowers
# these to bullet lists in the rendered output, which duplicates the GitBook
# left sidebar driven by SUMMARY.md. Strip them at the source so the
# rendered pages stay focused on prose + autodoc reference content.
_TOCTREE_BLOCK_RE = re.compile(
    r"\n?^```\{toctree\}.*?^```\s*$",
    re.DOTALL | re.MULTILINE,
)


def _strip_toctrees_in_tree(root: Path) -> None:
    """Remove every ``{toctree}`` block from Markdown files under ``root``."""
    for md in root.rglob("*.md"):
        text = md.read_text()
        new_text = _TOCTREE_BLOCK_RE.sub("", text)
        if new_text != text:
            md.write_text(new_text)


# After stripping grid and toctree blocks, some pages are left with section
# headings (``## Explore the Docs``) that no longer have any body. Remove
# such empty sections so they do not show up as blank entries in the
# rendered output.
#
# The match is intentionally restrictive: we only strip a heading whose body
# is empty *and* whose next heading is at the same or shallower level. That
# preserves the common pattern of an H2 that introduces a group of H3s
# without any prose of its own (e.g. the ``## Transport and client errors``
# header in reference/exceptions.md).
_HEADING_RE = re.compile(r"^(?P<hashes>#{1,6})\s+([^\n]+)$", re.MULTILINE)


def _strip_empty_sections(text: str) -> str:
    while True:
        headings = list(_HEADING_RE.finditer(text))
        if not headings:
            return text
        removed = False
        for idx, match in enumerate(headings):
            level = len(match.group("hashes"))
            if level < 2:
                continue
            body_start = match.end() + 1  # skip newline after heading
            if idx + 1 < len(headings):
                next_match = headings[idx + 1]
                next_level = len(next_match.group("hashes"))
                body = text[body_start:next_match.start()]
            else:
                next_level = 0  # treat EOF as "shallower" so trailing
                                # empty sections are also stripped
                body = text[body_start:]
            if next_level > level:
                # The next heading is a child of this one, so this heading
                # is acting as a section label even if it has no prose.
                continue
            if body.strip():
                continue
            # Strip the heading line and the blank lines that follow.
            text = text[: match.start()] + text[
                next_match.start() if idx + 1 < len(headings) else len(text):
            ]
            removed = True
            break
        if not removed:
            return text


# MyST admonition directives -> GitBook hint blocks. ``sphinx_markdown_builder``
# silently drops most admonitions ("unknown node type: <tip: ...>"), so we
# convert them to GitBook's native ``{% hint %}`` markup before Sphinx sees
# them. The mapping covers the standard MyST directives that share semantics
# with GitBook's four hint styles.
_ADMONITION_STYLES = {
    "tip": "info",
    "note": "info",
    "hint": "info",
    "important": "info",
    "attention": "warning",
    "caution": "warning",
    "warning": "warning",
    "danger": "danger",
    "error": "danger",
    "seealso": "info",
}
_ADMONITION_RE = re.compile(
    r"^```\{(?P<kind>"
    + "|".join(_ADMONITION_STYLES.keys())
    + r")\}\s*\n(?P<body>.*?)^```\s*$",
    re.DOTALL | re.MULTILINE,
)


def _convert_admonition(match: re.Match[str]) -> str:
    style = _ADMONITION_STYLES[match.group("kind")]
    body = match.group("body").rstrip()
    return f'{{% hint style="{style}" %}}\n{body}\n{{% endhint %}}'


def _convert_admonitions_in_tree(root: Path) -> None:
    """Apply ``_convert_admonition`` to every Markdown file under ``root``."""
    for md in root.rglob("*.md"):
        text = md.read_text()
        new_text = _ADMONITION_RE.sub(_convert_admonition, text)
        if new_text != text:
            md.write_text(new_text)


def _write_overlay_conf(conf_path: Path) -> None:
    """Replace the staged conf.py with an overlay that adds the markdown builder.

    ``sys.path`` is set up so the staged conf can still import the submodule's
    Python package for autodoc. We also disable the ``primary_sidebar_end``
    HTML-only option, which is harmless under the markdown builder but emits
    a warning.
    """
    overlay_template = '''"""Overlay Sphinx configuration for the GitBook markdown build.

This file is generated by scripts/build_api_client_python_docs.py. It re-uses
the upstream configuration from the api-client-python submodule and only adds
``sphinx_markdown_builder`` so the same source tree can be rendered as
GitBook-friendly Markdown.
"""

from __future__ import annotations

import os
import sys

SUBMODULE_SOURCE = __SUBMODULE_SOURCE__
SUBMODULE_ROOT = __SUBMODULE_ROOT__

# Allow autodoc to import the coinmetrics package directly from the submodule.
sys.path.insert(0, SUBMODULE_ROOT)
sys.path.insert(0, SUBMODULE_SOURCE)

# Re-export the upstream Sphinx config (project, extensions, autodoc options,
# myst extensions, intersphinx mappings, ...).
from conf import *  # noqa: F401,F403,E402

# The markdown builder is additive: it consumes the same parsed doctree the
# HTML builder would, including autodoc / sphinx-design / eval-rst output.
extensions = list(globals().get("extensions", []))
if "sphinx_markdown_builder" not in extensions:
    extensions.append("sphinx_markdown_builder")

# Belt-and-suspenders: the HTML theme options carry pydata-sphinx-theme keys
# that the markdown builder does not understand. Keep them but make the
# fallback explicit.
html_theme = globals().get("html_theme", "alabaster")

# Suppress noisy "toctree contains reference to nonexisting document"
# warnings for upstream pages we have not staged (e.g. examples.md).
suppress_warnings = list(globals().get("suppress_warnings", []))
for code in ("toc.not_included", "myst.xref_missing", "ref.doc", "toc.excluded"):
    if code not in suppress_warnings:
        suppress_warnings.append(code)

# GitBook hint blocks use ASCII double quotes inside ``{%% hint style="info" %%}``,
# so disable Sphinx's smart-quote transform that would otherwise rewrite them
# to curly Unicode quotes.
smartquotes = False
'''
    overlay = (
        overlay_template
        .replace("__SUBMODULE_SOURCE__", repr(str(SUBMODULE_DOCS_SOURCE)))
        .replace("__SUBMODULE_ROOT__", repr(str(SUBMODULE_ROOT)))
    )
    conf_path.write_text(overlay)


# ---------------------------------------------------------------------------
# Group page generation
# ---------------------------------------------------------------------------


def regenerate_group_pages() -> None:
    """Use the upstream ``_generate_groups.py`` classifier to scaffold one
    Sphinx page per ``CoinMetricsClient`` endpoint method.

    For each ``(slug, label)`` group returned by the classifier we write:

    * ``groups/<slug>/<method>.rst`` -- a tiny page whose title is
      ``CoinMetricsClient.<method>`` and whose body is a single
      ``.. automethod::`` directive. Sphinx renders these as one Markdown
      page each, which the output-assembly step relocates to
      ``reference/coinmetricsclient/<slug>/<method>.md``.
    * ``groups/<slug>/index.rst`` -- a per-group landing page whose title
      is the human-readable group label. This becomes the GitBook
      directory index (``coinmetricsclient/<slug>/README.md``).

    The slug -> methods mapping is captured into the module-level
    ``GROUP_METHODS`` so ``_render_summary`` and ``post_process_outputs``
    can drive sidebar nesting and per-group index content from the same
    source of truth.
    """
    src = STAGED_SOURCE / "reference" / "_generate_groups.py"
    if not src.is_file():
        raise SystemExit(f"Missing {src}; staging step did not complete.")

    spec = importlib.util.spec_from_file_location("_acp_generate_groups", src)
    if spec is None or spec.loader is None:
        raise SystemExit(f"Could not load {src}")
    module = importlib.util.module_from_spec(spec)
    # ``@dataclass`` looks up ``cls.__module__`` in ``sys.modules`` while
    # processing the class body, so the module must be registered before
    # exec_module runs.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)

    # Override the upstream constants so ``_collect_methods`` reads from
    # the real submodule rather than the staged tree.
    module.REPO_ROOT = SUBMODULE_ROOT
    module.API_CLIENT_PATH = SUBMODULE_ROOT / "coinmetrics" / "api_client.py"

    class_name = module.CLASS_NAME
    groups = module._collect_methods()

    output_dir = STAGED_SOURCE / "reference" / "groups"
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    GROUP_METHODS.clear()
    for slug, label in GROUP_PAGES:
        group = groups.get(slug)
        if not group or not group.methods:
            continue

        slug_dir = output_dir / slug
        slug_dir.mkdir()

        for method_name in group.methods:
            title = f"{class_name}.{method_name}"
            page_rst = (
                f"{title}\n{'=' * len(title)}\n\n"
                ".. currentmodule:: coinmetrics.api_client\n\n"
                f".. automethod:: {class_name}.{method_name}\n"
            )
            (slug_dir / f"{method_name}.rst").write_text(page_rst)

        # Per-group landing page (``coinmetricsclient/<slug>/README.md``).
        # Body is a hidden toctree so Sphinx wires the per-method pages
        # into the document graph (otherwise we get "document isn't
        # included in any toctree" warnings); the body content of the
        # landing page is generated separately during post-processing
        # from ``GROUP_METHODS`` because the markdown builder strips the
        # rendered toctree anyway.
        index_rst_lines = [
            label,
            "=" * len(label),
            "",
            ".. toctree::",
            "   :hidden:",
            "   :maxdepth: 1",
            "",
        ]
        for method_name in group.methods:
            index_rst_lines.append(f"   {method_name}")
        index_rst_lines.append("")
        (slug_dir / "index.rst").write_text("\n".join(index_rst_lines))

        GROUP_METHODS[slug] = list(group.methods)


def _ensure_submodule_importable() -> None:
    """Insert the submodule root onto ``sys.path`` so ``coinmetrics`` resolves.

    The build venv installs the submodule with ``pip install -e ...`` for
    autodoc, but when this script is run outside that venv (e.g. from a
    plain ``python3`` invocation) we still need to be able to introspect
    the package to scaffold the per-class pages.
    """
    submodule_path = str(SUBMODULE_ROOT)
    if submodule_path not in sys.path:
        sys.path.insert(0, submodule_path)


def _public_methods(cls: type) -> List[str]:
    """Return the names of public methods / properties declared on ``cls``.

    Walks ``vars(cls)`` so we only pick up symbols defined directly on the
    class (not inherited from ``object``), and preserves the source order
    by using ``dict.__iter__`` (which is insertion order in CPython 3.7+).
    Inherited ``BaseException`` machinery from ``Exception`` subclasses is
    therefore filtered out automatically.
    """
    import inspect

    methods: List[str] = []
    for name, value in vars(cls).items():
        if name.startswith("_"):
            continue
        if inspect.isfunction(value) or isinstance(
            value, (property, staticmethod, classmethod)
        ):
            methods.append(name)
    return methods


def regenerate_class_pages() -> None:
    """Scaffold per-method pages for every class in ``EXTRA_CLASS_PAGES``.

    For each class we write:

    * ``reference/<slug>/<method>.rst`` -- a Sphinx page whose title is
      ``ClassName.method`` and whose body is a single ``automethod``.
    * ``reference/<slug>/index.rst`` -- a class landing page with the
      ``autoclass`` signature (``:no-members:`` so the per-method pages are
      not duplicated inline) and a hidden toctree wiring the method pages
      into the document graph.
    """
    _ensure_submodule_importable()
    import importlib

    EXTRA_CLASS_METHODS.clear()
    EXTRA_CLASS_QUALIFIERS.clear()
    reference_dir = STAGED_SOURCE / "reference"

    for slug, label, module_path, class_name in EXTRA_CLASS_PAGES:
        module = importlib.import_module(module_path)
        cls = getattr(module, class_name)
        methods = _public_methods(cls)
        EXTRA_CLASS_QUALIFIERS[slug] = f"{module_path}.{class_name}"

        slug_dir = reference_dir / slug
        if slug_dir.exists():
            shutil.rmtree(slug_dir)
        slug_dir.mkdir(parents=True)

        for method_name in methods:
            title = f"{class_name}.{method_name}"
            page_rst = (
                f"{title}\n{'=' * len(title)}\n\n"
                f".. currentmodule:: {module_path}\n\n"
                f".. automethod:: {class_name}.{method_name}\n"
            )
            (slug_dir / f"{method_name}.rst").write_text(page_rst)

        index_lines = [
            label,
            "=" * len(label),
            "",
            f".. currentmodule:: {module_path}",
            "",
            f".. autoclass:: {class_name}",
            "   :no-members:",
            "",
            ".. toctree::",
            "   :hidden:",
            "   :maxdepth: 1",
            "",
        ]
        for method_name in methods:
            index_lines.append(f"   {method_name}")
        index_lines.append("")
        (slug_dir / "index.rst").write_text("\n".join(index_lines))

        EXTRA_CLASS_METHODS[slug] = methods


def regenerate_exception_pages() -> None:
    """Scaffold one page per exception class in ``coinmetrics._exceptions``.

    The exception hierarchy is small (currently ~7 classes) and shares no
    common landing prose, so each class gets a dedicated
    ``reference/exceptions/<ClassName>.rst`` page that renders the
    ``autoexception`` directive, plus an ``index.rst`` listing them.
    """
    _ensure_submodule_importable()
    import importlib

    module = importlib.import_module(EXCEPTIONS_MODULE)
    classes = sorted(
        name
        for name, value in vars(module).items()
        if isinstance(value, type)
        and issubclass(value, BaseException)
        and value.__module__ == EXCEPTIONS_MODULE
        and not name.startswith("_")
    )
    EXCEPTION_CLASSES.clear()
    EXCEPTION_CLASSES.extend(classes)

    slug_dir = STAGED_SOURCE / "reference" / EXCEPTIONS_SLUG
    if slug_dir.exists():
        shutil.rmtree(slug_dir)
    slug_dir.mkdir(parents=True)

    for cls_name in classes:
        page_rst = (
            f"{cls_name}\n{'=' * len(cls_name)}\n\n"
            f".. currentmodule:: {EXCEPTIONS_MODULE}\n\n"
            f".. autoexception:: {cls_name}\n"
            "   :members:\n"
            "   :show-inheritance:\n"
        )
        (slug_dir / f"{cls_name}.rst").write_text(page_rst)

    index_lines = [
        EXCEPTIONS_LABEL,
        "=" * len(EXCEPTIONS_LABEL),
        "",
        "The Coin Metrics Python client raises a small hierarchy of typed "
        "exceptions for HTTP errors, rate limiting, transport failures and "
        "data-collection errors. All exception classes are exported from "
        "the top-level ``coinmetrics`` package.",
        "",
        ".. toctree::",
        "   :hidden:",
        "   :maxdepth: 1",
        "",
    ]
    for cls_name in classes:
        index_lines.append(f"   {cls_name}")
    index_lines.append("")
    (slug_dir / "index.rst").write_text("\n".join(index_lines))


# ---------------------------------------------------------------------------
# Sphinx build
# ---------------------------------------------------------------------------


def run_sphinx() -> None:
    _wipe(STAGED_BUILD)
    STAGED_BUILD.mkdir(parents=True)
    cmd = [
        sys.executable,
        "-m",
        "sphinx",
        "-b",
        "markdown",
        "-q",
        str(STAGED_SOURCE),
        str(STAGED_BUILD),
    ]
    print("$ " + " ".join(cmd))
    result = subprocess.run(cmd, cwd=str(REPO_ROOT))
    if result.returncode != 0:
        raise SystemExit(f"sphinx-build exited with {result.returncode}")


# ---------------------------------------------------------------------------
# Output assembly
# ---------------------------------------------------------------------------


def reset_output(output_root: Path) -> None:
    """Wipe ``output_root`` so the build starts from a known clean state.

    Only ``PRESERVED_PATHS`` survive (``.gitbook.yaml`` is kept because it
    pins the GitBook space configuration and is not produced by the build).
    Everything else, including ``SUMMARY.md`` and ``.gitbook/assets/``, is
    removed up front so a previous run cannot leave stale files behind.
    """
    if not output_root.exists():
        output_root.mkdir(parents=True)
        return
    for entry in output_root.iterdir():
        if entry.name in PRESERVED_PATHS:
            continue
        if entry.is_dir():
            shutil.rmtree(entry)
        else:
            entry.unlink()


def collect_outputs(output_root: Path) -> None:
    """Move/rename generated Markdown files into ``output_root``."""
    if not STAGED_BUILD.is_dir():
        raise SystemExit(f"Sphinx build directory missing: {STAGED_BUILD}")

    # Slug prefixes whose per-method/per-class child pages should keep
    # underscores in their filenames (Python identifiers map 1:1 to the
    # method names in the URL).
    underscore_preserving_prefixes = (
        "reference/groups/",
        f"reference/{EXCEPTIONS_SLUG}/",
    ) + tuple(f"reference/{slug}/" for slug, *_ in EXTRA_CLASS_PAGES)

    for src in STAGED_BUILD.rglob("*.md"):
        rel = src.relative_to(STAGED_BUILD).as_posix()
        target_rel = PAGE_RENAMES.get(rel)
        if target_rel is None:
            if rel.startswith("reference/groups/"):
                target_rel = rel.replace(
                    "reference/groups/", "reference/coinmetricsclient/", 1
                )
            elif any(rel.startswith(p) for p in underscore_preserving_prefixes):
                target_rel = rel
            else:
                target_rel = rel.replace("_", "-")
        target = output_root / target_rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, target)


def copy_assets(output_root: Path) -> None:
    """Mirror static images into the GitBook assets folder.

    The assets directory is wiped first so images removed upstream do not
    linger in the committed output.
    """
    src_dir = SUBMODULE_DOCS_SOURCE / "_static" / "images"
    assets_dir = output_root / GITBOOK_ASSETS_REL
    if assets_dir.exists():
        shutil.rmtree(assets_dir)
    if not src_dir.is_dir():
        return
    assets_dir.mkdir(parents=True, exist_ok=True)
    for image in src_dir.iterdir():
        if image.is_file():
            shutil.copy2(image, assets_dir / image.name)


# ---------------------------------------------------------------------------
# Post-processing
# ---------------------------------------------------------------------------


_RESIDUAL_TOCTREE_RE = re.compile(
    r"^```\{toctree\}.*?^```\s*$",
    re.DOTALL | re.MULTILINE,
)
_RESIDUAL_EVAL_RST_RE = re.compile(
    r"^```\{eval-rst\}.*?^```\s*$",
    re.DOTALL | re.MULTILINE,
)
_STATIC_IMAGE_RE = re.compile(r"_static/images/")

# ``sphinx_markdown_builder`` emits the Sphinx ``:returns:`` and ``:rtype:``
# field-list entries as two separate top-level bullets:
#
#     * **Returns:**
#       <description>
#     * **Return type:**
#       <type>
#
# Both are part of the same logical "what does this method return?"
# block, so combine them into a single ``Returns`` heading with the
# return type as a top-level bullet and the description (if any) as a
# nested bullet underneath. Also handles the (much more common) case
# where only the ``Return type`` bullet is present.
_RETURNS_BLOCK_RE = re.compile(
    r"(?:^\* \*\*Returns:\*\*\n[ \t]+(?P<desc>[^\n]+)\n)?"
    r"^\* \*\*Return type:\*\*\n[ \t]+(?P<type>[^\n]+)",
    re.MULTILINE,
)


def _rewrite_returns_block(match: re.Match[str]) -> str:
    desc = match.group("desc")
    rtype = match.group("type")
    # Leading blank line ensures the previous bullet list (Parameters)
    # is closed before the ``**Returns:**`` paragraph starts.
    lines = ["", "**Returns:**", "", f"* {rtype}"]
    if desc:
        lines.append(f"  * {desc}")
    return "\n".join(lines)

# ``sphinx_markdown_builder`` rewrites every cross-reference to use a ``.md``
# extension, including the intersphinx links that resolve to external HTML
# documentation. Detect and fix the external ones.
_INTERSPHINX_HOSTS = (
    "docs.python.org",
    "pandas.pydata.org",
    "numpy.org",
)
_INTERSPHINX_RE = re.compile(
    r"(\]\(https?://(?:" + "|".join(re.escape(h) for h in _INTERSPHINX_HOSTS) + r")[^)\s]*?)\.md(?=[)#])"
)

# Autodoc rendering. ``sphinx-markdown-builder`` emits headings like
#
#     ### *class* coinmetrics.api_client.CoinMetricsClient(api_key='', ...)
#     #### CoinMetricsClient.get_asset_metrics(assets, ...)
#     #### *property* CoinMetricsClient.foo
#
# These have two problems for GitBook:
#
# 1. The full signature ends up in the heading text. GitBook's right-hand
#    "On this page" panel shows headings as anchor links, so a 200-character
#    constructor signature is unusable as navigation.
# 2. Sphinx's intra-doc cross-references resolve to anchors named after the
#    fully-qualified Python path (``coinmetrics.api_client.CoinMetricsClient``),
#    but GitBook slugifies headings into something completely different, so
#    every ``[Foo](page.md#coinmetrics.x.Foo)`` link is silently broken.
#
# We rewrite each autodoc heading into:
#
#     <a id="coinmetrics.api_client.CoinMetricsClient"></a>
#
#     ### *class* CoinMetricsClient
#
#     ```python
#     class coinmetrics.api_client.CoinMetricsClient(
#         api_key='',
#         verify_ssl_certs=True,
#         ...
#     )
#     ```
#
# which gives GitBook a clean short heading, a stable anchor that matches
# Sphinx's cross-link IDs, and the full pydata-style signature underneath.
#
# Method headings (``#### CoinMetricsClient.foo``) are also promoted to H3
# so they appear in GitBook's "On this page" right-hand panel.

# Kinds where the heading payload contains the FULLY-QUALIFIED dotted path
# (sphinx-markdown-builder always emits class/exception/function with the
# module prefix, regardless of ``.. currentmodule::``).
_QUALIFIED_KINDS = frozenset({"class", "exception", "function", "data"})
_AUTODOC_KIND_RE = re.compile(
    r"^(?P<hashes>#{2,5})\s+"
    r"\*(?P<kind>class|exception|function|method|static|staticmethod|"
    r"classmethod|abstractmethod|abstract|property|attribute|data)\*\s+"
    r"(?P<rest>\S.*?)\s*$"
)
# Plain method/function headings without an explicit kind label, e.g.
# ``#### CoinMetricsClient.get_asset_metrics(...)`` or ``#### run(...)``.
# Match identifiers (with optional dotted path) followed by an optional
# parenthesised argument list, but NOT bare prose headings like
# ``## Endpoints``.
_AUTODOC_PLAIN_RE = re.compile(
    r"^(?P<hashes>#{2,5})\s+"
    r"(?P<rest>"
    r"[A-Za-z_]\w*(?:\\?\.[\w\\]+)+(?:\([^\n]*\))?"  # dotted name (+optional args)
    r"|[A-Za-z_]\w*\([^\n]*\)"                        # bare name + args
    r")\s*$"
)


def _unescape_sig(sig: str) -> str:
    """Drop the ``\\*`` / ``\\_`` escapes the markdown builder injects.

    These escapes are needed in plain Markdown so ``**kwargs`` does not
    render as bold, but inside a code block they would render literally.
    """
    return sig.replace("\\*", "*").replace("\\_", "_")


def _split_signature(payload: str) -> Tuple[str, Optional[str]]:
    """Split ``Foo.bar(arg=1, arg2)`` into ``("Foo.bar", "arg=1, arg2")``.

    Returns ``(dotted_name, None)`` if the payload has no parenthesised
    argument list (e.g. property / attribute signatures).
    """
    payload = payload.strip()
    if "(" not in payload:
        return payload, None
    # Match the FIRST opening parenthesis and take everything to the matching
    # closing one. The args may themselves contain balanced parens (default
    # values like ``factory()``); walk the string to find the right close.
    open_idx = payload.index("(")
    depth = 0
    for i, ch in enumerate(payload[open_idx:], start=open_idx):
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return payload[:open_idx], payload[open_idx + 1 : i]
    # Unbalanced -- fall back to a simple split.
    return payload[:open_idx], payload[open_idx + 1 :].rstrip(") ")


# Human-readable label rendered as the italic kind annotation that
# pydata-sphinx-theme prints to the left of every API signature ("method",
# "property", "classmethod", ...). Maps the canonical autodoc kind
# emitted by sphinx-markdown-builder to the label Sphinx itself uses.
_KIND_LABELS = {
    "class": "class",
    "exception": "exception",
    "function": "function",
    "method": "method",
    "static": "static method",
    "staticmethod": "static method",
    "classmethod": "classmethod",
    "abstract": "abstract method",
    "abstractmethod": "abstract method",
    "property": "property",
    "attribute": "attribute",
    "data": "data",
}


def _format_pydata_signature_block(
    kind: Optional[str],
    prefix: str,
    full_dotted: str,
    args: Optional[str],
) -> List[str]:
    """Return the lines for an italic kind label + a signature code block.

    Mirrors the way pydata-sphinx-theme renders an API signature: a small
    italic annotation (``method``, ``property``, ``classmethod``, ...) sits
    just above a monospace signature block. In Markdown we use an
    italic-emphasis line followed by a python-fenced code block.
    """
    label = _KIND_LABELS.get(kind) if kind else None
    block = _format_signature_block(prefix, full_dotted, args)
    if label:
        return [f"*{label}*", "", block]
    return [block]


def _format_signature_block(prefix: str, full_dotted: str, args: Optional[str]) -> str:
    """Render the ``python``-fenced signature block printed under each heading."""
    head = f"{prefix} {full_dotted}".strip()
    if args is None:
        body = head
    else:
        # Split args on top-level commas (so ``Dict[str, int]`` stays intact)
        # and put each on its own line for readability.
        pieces: List[str] = []
        depth = 0
        current = ""
        for ch in args:
            if ch in "([{":
                depth += 1
            elif ch in ")]}":
                depth -= 1
            if ch == "," and depth == 0:
                pieces.append(current.strip())
                current = ""
            else:
                current += ch
        if current.strip():
            pieces.append(current.strip())
        if len(pieces) <= 1 or sum(len(p) for p in pieces) + len(head) < 80:
            body = f"{head}({args.strip()})"
        else:
            body = head + "(\n    " + ",\n    ".join(pieces) + ",\n)"
    return "```python\n" + body + "\n```"


def _emit_autodoc_heading(
    kind: Optional[str],
    display_name: str,
    anchor: str,
    full_dotted: str,
    args: Optional[str],
    *,
    level_override: Optional[str] = None,
) -> List[str]:
    """Build the multi-line replacement for a single autodoc heading.

    ``display_name`` is the human-readable text rendered inside the heading.
    For class / exception / function it is the short symbol name
    (``CoinMetricsClient``). For method / property / attribute headings it
    is the qualified ``ClassName.symbol`` form -- this matches Sphinx's
    native pydata rendering and, more importantly for GitBook, makes every
    method heading globally unique so it ranks well in the search bar.

    The display name is wrapped in backticks so it renders in a monospace
    "code" face, mirroring the pydata-sphinx-theme look.

    Heading levels are normalised so GitBook's "On this page" right-hand
    panel surfaces them consistently:

    * ``class`` / ``exception`` -> ``##`` (top-level section on the page).
    * Everything else (methods, properties, attributes, functions, data) ->
      ``###`` (visually nested under their parent class on class pages, or
      top-level on group pages where there is no class heading).
    """
    # pydata-sphinx-theme renders the entire autodoc signature as a
    # single inline code-formatted line, e.g.
    # ``class pandas.DataFrame(data=None, index=None, ...)``. The kind
    # keyword sits inside the code span; there is no separate heading,
    # multi-line code block or italic prefix above the signature. We
    # mirror that here as a single ``## `<kind?> <dotted>(<args>)``` H2
    # so the entire signature is the heading, GitBook lists it in the
    # "On this page" panel, and the page contains no redundant
    # multi-line code block beneath it.
    if kind in {"class", "exception"}:
        prefix = kind
    elif kind in {"static", "staticmethod"}:
        prefix = "static"
    elif kind == "classmethod":
        prefix = "classmethod"
    elif kind in {"abstract", "abstractmethod"}:
        prefix = "abstract"
    elif kind == "property":
        prefix = "property"
    else:
        # Plain methods / functions / attributes / data: no kind keyword
        # in the signature, matching how pydata renders ordinary methods
        # (``DataFrame.head(n=5)``).
        prefix = ""

    # Render the signature as a python-fenced code block. This gives the
    # signature syntax highlighting (matching the pydata-sphinx-theme
    # look where the kind keyword and arguments are colorised) and
    # cleanly wraps long parameter lists across multiple lines via
    # ``_format_signature_block``.
    return [
        f'<a id="{anchor}"></a>',
        "",
        _format_signature_block(prefix, full_dotted, args),
    ]


def _resolve_anchor(
    dotted: str,
    kind: Optional[str],
    class_qualifier: Optional[str],
    module_qualifier: Optional[str],
) -> Tuple[str, str]:
    """Figure out the anchor ID and full dotted path for a heading.

    Returns ``(anchor, full_dotted)``.

    * For class/exception/function/data kinds, the heading payload already
      includes the fully-qualified module path; we use it as-is.
    * For method/property/attribute headings on a documented class, the
      payload may be ``Class.method`` (when emitted under a
      ``currentmodule`` directive) or just ``method`` (when emitted by
      ``automethod`` against a class set as the current context). We
      prepend the module qualifier and the class name as needed.
    """
    if kind in _QUALIFIED_KINDS or "coinmetrics" in dotted:
        return dotted, dotted

    parts = dotted.split(".")
    if class_qualifier:
        # ``class_qualifier`` is itself fully qualified (e.g.
        # ``coinmetrics.api_client.CoinMetricsClient``).
        class_short = class_qualifier.rsplit(".", 1)[-1]
        if parts[0] == class_short:
            full = class_qualifier.rsplit(".", 1)[0] + "." + ".".join(parts)
        else:
            full = class_qualifier + "." + ".".join(parts)
        return full, full

    if module_qualifier:
        full = module_qualifier + "." + ".".join(parts)
        return full, full

    # No context to qualify with -- use the dotted name verbatim. This will
    # not match Sphinx's cross-link anchors but at least keeps the page
    # rendering correctly.
    return dotted, dotted


def _is_per_method_page(page_rel: str) -> bool:
    """Identify pages whose H1 already names the symbol they document.

    On these pages ``automethod`` / ``autoexception`` would emit a redundant
    inline heading just below the H1 -- ``_transform_autodoc_headings``
    drops it so only the page title and the signature block remain. Covers:

    * ``reference/coinmetricsclient/<group>/<method>.md`` (CoinMetricsClient
      endpoint methods)
    * ``reference/<class-slug>/<method>.md`` for each entry in
      ``EXTRA_CLASS_PAGES``
    * ``reference/exceptions/<ExceptionClass>.md``
    """
    parts = page_rel.split("/")
    if not (parts and parts[0] == "reference" and parts[-1].endswith(".md")):
        return False
    if parts[-1] == "README.md":
        return False
    if len(parts) == 4 and parts[1] == "coinmetricsclient":
        return True
    if len(parts) == 3:
        slugs = {slug for slug, *_ in EXTRA_CLASS_PAGES}
        slugs.add(EXCEPTIONS_SLUG)
        return parts[1] in slugs
    return False


def _transform_autodoc_headings(text: str, page_rel: str) -> str:
    """Rewrite every autodoc heading on the page (see module-level comment).

    ``page_rel`` is the output-relative path of the file (e.g.
    ``reference/coinmetricsclient/timeseries/get_asset_metrics.md``). It is
    used to (a) seed the class qualifier on pages where Sphinx does not
    emit a ``*class*`` heading (per-method and cm-stream pages) and (b)
    suppress the inline method heading on per-method pages -- those pages
    already carry the method name in the H1 from the RST title.
    """
    # Resolve the per-page default class qualifier. Group pages match by
    # directory prefix; everything else by exact path.
    class_qualifier: Optional[str] = None
    module_qualifier: Optional[str] = None
    for prefix, qualifier in PAGE_DEFAULT_CLASS_QUALIFIER.items():
        if page_rel.startswith(prefix) or page_rel == prefix:
            class_qualifier = qualifier
            module_qualifier = qualifier.rsplit(".", 1)[0]
            break

    # On per-method pages, the page H1 already says
    # ``CoinMetricsClient.<method>``, so the inline H3 produced by
    # ``automethod`` would duplicate it. Strip it down to the signature
    # block + anchor (no heading line).
    suppress_method_heading = _is_per_method_page(page_rel)

    # On per-method / per-exception pages, mirror the layout of the
    # class definition pages (e.g. ``reference/data-collection/README.md``):
    # a plain-text H1 from the RST title, an HTML anchor for cross-links,
    # then a single ``## `<kind> <Class.symbol>``` H2 followed by the
    # python signature block. The transformations below promote the
    # ``automethod`` / ``autoexception`` heading to H2 instead of letting
    # it default to H3, so the in-page outline matches the class pages.
    promote_heading_to_h2 = suppress_method_heading

    out: List[str] = []

    def _append_block(block: List[str]) -> None:
        # Ensure a blank line precedes the inline HTML anchor; without it
        # CommonMark may glue the anchor onto the previous heading or
        # paragraph, suppressing the rewritten heading entirely.
        if out and out[-1].strip():
            out.append("")
        out.extend(block)

    def _qualified_method_name(dotted: str) -> str:
        """``Class.method`` form for use as the displayed heading text."""
        short = dotted.rsplit(".", 1)[-1]
        if class_qualifier:
            class_short = class_qualifier.rsplit(".", 1)[-1]
            # Avoid double-prefixing if Sphinx already emitted ``Class.method``.
            if dotted.startswith(class_short + "."):
                return dotted
            return f"{class_short}.{short}"
        return short

    for line in text.split("\n"):
        m = _AUTODOC_KIND_RE.match(line)
        if m:
            kind = m.group("kind")
            payload = _unescape_sig(m.group("rest"))
            dotted, args = _split_signature(payload)
            if kind in {"class", "exception"}:
                # Reset the class context for subsequent method headings.
                class_qualifier = dotted
                module_qualifier = dotted.rsplit(".", 1)[0]
                display = dotted.rsplit(".", 1)[-1]
                anchor, full = dotted, dotted
            elif kind == "function":
                # Module-level functions have no enclosing class to qualify
                # with; render them with their short name.
                display = dotted.rsplit(".", 1)[-1]
                anchor, full = dotted, dotted
            else:
                anchor, full = _resolve_anchor(
                    dotted, kind, class_qualifier, module_qualifier
                )
                display = _qualified_method_name(dotted)
            _append_block(
                _emit_autodoc_heading(
                    kind,
                    display_name=display,
                    anchor=anchor,
                    full_dotted=full,
                    args=args,
                    level_override="##" if promote_heading_to_h2 else None,
                )
            )
            continue

        m = _AUTODOC_PLAIN_RE.match(line)
        if m:
            payload = _unescape_sig(m.group("rest"))
            dotted, args = _split_signature(payload)
            anchor, full = _resolve_anchor(
                dotted, None, class_qualifier, module_qualifier
            )
            # Plain headings (no explicit kind label in the source) are
            # emitted by ``automethod`` for ordinary methods, so render
            # them with the ``method`` annotation to match the class
            # pages, where every member has a kind keyword in its
            # heading.
            _append_block(
                _emit_autodoc_heading(
                    kind="method" if promote_heading_to_h2 else None,
                    display_name=_qualified_method_name(dotted),
                    anchor=anchor,
                    full_dotted=full,
                    args=args,
                    level_override="##" if promote_heading_to_h2 else None,
                )
            )
            continue

        out.append(line)

    return "\n".join(out)


def post_process_file(path: Path, output_root: Path) -> None:
    text = path.read_text()
    original = text

    # Belt-and-suspenders: ``sphinx_markdown_builder`` consumes ``{toctree}``
    # and ``{eval-rst}`` blocks itself, but if anything slips through (for
    # example because the staged file failed to parse) we strip it here.
    text = _RESIDUAL_TOCTREE_RE.sub("", text)
    text = _RESIDUAL_EVAL_RST_RE.sub("", text)

    # Restore the correct extension on intersphinx URLs the markdown builder
    # mistakenly rewrote to ``.md``.
    text = _INTERSPHINX_RE.sub(r"\1.html", text)

    # The submodule's reference/coinmetricsclient.md toctree points at
    # ``groups/<slug>``. We relocate those generated pages under
    # ``coinmetricsclient/`` so they nest beneath their parent in the GitBook
    # sidebar, so rewrite the parent page's links to match.
    text = re.sub(r"\]\(groups/", "](coinmetricsclient/", text)

    # ``myst-parser`` strips the URL out of links whose target it cannot
    # resolve (e.g. references to documents we have not staged), leaving
    # ``[Label]()``. GitBook would render that as a broken link, so collapse
    # such patterns down to plain text.
    text = re.sub(r"\[([^\]]+)\]\(\)", r"\1", text)

    # The MyST sources reference logos as ``_static/images/...``. The static
    # tree is not copied into the GitBook output, so rewrite to the assets
    # path that GitBook understands. A leading slash makes the reference
    # absolute relative to the space root, which works from any depth.
    text = _STATIC_IMAGE_RE.sub("/.gitbook/assets/", text)

    try:
        rel_to_root = path.relative_to(output_root).as_posix()
    except ValueError:
        rel_to_root = ""

    # Replace the H1 title for sphinx-apidoc-generated pages. The default is
    # ``# coinmetrics.<module> module`` (with backslash-escaped underscores
    # for private modules), which is awkward and exposes the implementation
    # detail of which file a class lives in.
    desired_title = PAGE_TITLES.get(rel_to_root)
    if desired_title is not None:
        text = re.sub(
            r"\A#\s+coinmetrics(?:\\?\.|\.)\\?[\w\\]+\s+module\s*\n",
            f"# {desired_title}\n",
            text,
        )

    # Drop section headings whose body was removed by earlier processing
    # (e.g. ``## Explore the Docs`` after the grid block beneath it was
    # stripped from the source). Done before the autodoc-heading rewrites
    # below so we do not match against a heading that is about to be
    # wrapped in backticks.
    text = _strip_empty_sections(text)

    # Rewrite Sphinx autodoc headings into a GitBook-friendly form: short
    # heading text (just the symbol name), an HTML anchor matching the
    # Sphinx cross-reference ID, and the full signature in a code block.
    # Only apply to the reference tree -- the narrative pages have ordinary
    # headings we should not touch.
    if rel_to_root.startswith("reference/"):
        text = _transform_autodoc_headings(text, rel_to_root)
        # Combine the separate ``Returns:`` and ``Return type:`` bullets
        # into a single ``Returns`` block with the type as a top-level
        # bullet and the description (when present) nested below.
        text = _RETURNS_BLOCK_RE.sub(_rewrite_returns_block, text)

    # Rewrite intra-doc links that refer to the legacy (underscore or
    # ``index.md``) names of files we have renamed via PAGE_RENAMES.
    # We only need to rewrite the *trailing* portion of the link target so
    # we cover both same-directory references (``data_collection.md``) and
    # parent-relative ones (``reference/api_client.md``).
    #
    # Apply longer source names first so ``parallel_data_collection.md`` is
    # matched before ``data_collection.md`` (which is a suffix of it).
    rename_pairs = sorted(
        PAGE_RENAMES.items(),
        key=lambda item: len(Path(item[0]).name),
        reverse=True,
    )
    for src_rel, target_rel in rename_pairs:
        src_name = Path(src_rel).name
        target_name = Path(target_rel).name
        if src_name == target_name:
            continue
        # Anchor on a ``/`` or ``(`` so we don't slice into longer filenames
        # that happen to end with ``src_name`` (e.g. ``parallel_data_collection``
        # -> ``data_collection``).
        pattern = re.compile(
            r"(\]\((?:[^)#\s]*?[/(])?)" + re.escape(src_name) + r"(?=[)#])"
        )
        text = pattern.sub(lambda m, t=target_name: m.group(1) + t, text)
        # Same-directory bare references like ``](data_collection.md)``.
        text = re.sub(
            r"\]\(" + re.escape(src_name) + r"(?=[)#])",
            f"]({target_name}",
            text,
        )

    if text != original:
        path.write_text(text)


def post_process_outputs(output_root: Path) -> None:
    for md in output_root.rglob("*.md"):
        if md.name == "SUMMARY.md":
            continue
        post_process_file(md, output_root)


def write_group_index_pages(output_root: Path) -> None:
    """Generate the README landing page for every per-method section.

    Three flavours of section are produced:

    * Endpoint groups under ``reference/coinmetricsclient/<slug>/`` --
      the README is fully rewritten because Sphinx renders the staged
      ``index.rst`` into a near-empty page (just the H1 from the title).
      We replace it with a short description plus a bullet list linking
      every method in the group.
    * Per-class sections (``reference/<slug>/`` for DataCollection,
      ParallelDataCollection, CmStream) -- the README produced by Sphinx
      already contains the ``autoclass`` signature block, so we *append*
      a "Methods" list to the existing file rather than overwriting it.
    * Exceptions (``reference/exceptions/``) -- README is rewritten
      with a short intro and a bullet list of exception classes.
    """
    # CoinMetricsClient endpoint groups -- full rewrite.
    for slug, label in GROUP_PAGES:
        methods = GROUP_METHODS.get(slug)
        if not methods:
            continue
        readme = output_root / "reference" / "coinmetricsclient" / slug / "README.md"
        readme.parent.mkdir(parents=True, exist_ok=True)
        lines: List[str] = [f"# {label}", ""]
        lines.append(
            "Endpoint methods on "
            "[`CoinMetricsClient`](../../coinmetricsclient.md) that hit "
            f"the `{slug}` endpoint root."
        )
        lines.append("")
        for method_name in methods:
            lines.append(
                f"* [`CoinMetricsClient.{method_name}`]({method_name}.md)"
            )
        lines.append("")
        readme.write_text("\n".join(lines))

    # Per-class sections -- append a "Methods" list under the autoclass
    # signature so both the class definition and the navigable method
    # list are visible on the landing page.
    for slug, _label, _module, class_name in EXTRA_CLASS_PAGES:
        methods = EXTRA_CLASS_METHODS.get(slug)
        if not methods:
            continue
        readme = output_root / "reference" / slug / "README.md"
        if not readme.is_file():
            continue
        existing = readme.read_text().rstrip()
        appendix: List[str] = ["", "", "### Methods", ""]
        for method_name in methods:
            appendix.append(
                f"* [`{class_name}.{method_name}`]({method_name}.md)"
            )
        appendix.append("")
        readme.write_text(existing + "\n".join(appendix))

    # Exceptions section -- full rewrite.
    if EXCEPTION_CLASSES:
        readme = output_root / "reference" / EXCEPTIONS_SLUG / "README.md"
        readme.parent.mkdir(parents=True, exist_ok=True)
        lines = [f"# {EXCEPTIONS_LABEL}", ""]
        lines.append(
            "The Coin Metrics Python client raises a typed exception "
            "hierarchy for HTTP errors, rate limiting, transport failures "
            "and data-collection errors. All exception classes are "
            "exported from the top-level `coinmetrics` package."
        )
        lines.append("")
        for cls_name in EXCEPTION_CLASSES:
            lines.append(f"* [`{cls_name}`]({cls_name}.md)")
        lines.append("")
        readme.write_text("\n".join(lines))


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--keep-staging",
        action="store_true",
        help="Do not delete .docs-build after the build (useful for debugging).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT,
        help=(
            "Directory the rendered GitBook space is written to. Defaults to "
            "spaces/api-client-python/docs."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Build into a scratch directory and diff against --output. Exit "
            "non-zero if the committed output is not byte-for-byte identical "
            "to what the pipeline would produce. Used by CI to ensure every "
            "iteration of the GitBook space is reproducible from the script."
        ),
    )
    return parser.parse_args(list(argv))


def build(output_root: Path) -> None:
    """Run the full pipeline, writing the rendered space into ``output_root``."""
    print(f"Staging source from {SUBMODULE_DOCS_SOURCE} -> {STAGED_SOURCE}")
    stage_source()
    print("Regenerating per-endpoint group pages")
    regenerate_group_pages()
    print("Regenerating per-method pages for DataCollection / CmStream")
    regenerate_class_pages()
    print("Regenerating per-class pages for the exceptions module")
    regenerate_exception_pages()
    print(f"Running sphinx-build (markdown) -> {STAGED_BUILD}")
    run_sphinx()
    print(f"Resetting {output_root} (preserving {sorted(PRESERVED_PATHS)})")
    reset_output(output_root)
    print("Copying generated Markdown into the GitBook space")
    collect_outputs(output_root)
    print("Copying static image assets")
    copy_assets(output_root)
    print("Post-processing generated Markdown for GitBook")
    post_process_outputs(output_root)
    print("Writing per-group landing pages")
    write_group_index_pages(output_root)
    print("Writing SUMMARY.md")
    write_summary(output_root)


def _diff_trees(expected: Path, actual: Path) -> List[str]:
    """Return a list of human-readable lines describing differences.

    The two trees are compared by file content (not mtime). Files matching
    ``PRESERVED_PATHS`` are skipped because they live outside the build's
    scope. Returns an empty list if the trees are identical.
    """
    diffs: List[str] = []

    def _walk(rel: Path) -> None:
        exp_dir = expected / rel
        act_dir = actual / rel
        cmp = filecmp.dircmp(exp_dir, act_dir)
        for name in sorted(cmp.left_only):
            if rel == Path(".") and name in PRESERVED_PATHS:
                continue
            diffs.append(f"  only in committed output: {(rel / name).as_posix()}")
        for name in sorted(cmp.right_only):
            if rel == Path(".") and name in PRESERVED_PATHS:
                continue
            diffs.append(f"  only in fresh build:       {(rel / name).as_posix()}")
        # ``filecmp.dircmp`` defaults to a shallow comparison (mtime + size);
        # rerun with full content comparison for the candidate matches.
        match, mismatch, errors = filecmp.cmpfiles(
            exp_dir, act_dir, cmp.common_files, shallow=False
        )
        for name in sorted(mismatch + errors):
            if rel == Path(".") and name in PRESERVED_PATHS:
                continue
            diffs.append(f"  differs: {(rel / name).as_posix()}")
        for name in sorted(cmp.common_dirs):
            _walk(rel / name)

    _walk(Path("."))
    return diffs


def _show_text_diff(expected: Path, actual: Path, rel: str, max_lines: int = 60) -> None:
    """Print a unified diff for a single mismatched file (best-effort)."""
    try:
        result = subprocess.run(
            ["diff", "-u", str(expected / rel), str(actual / rel)],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return
    out = result.stdout.splitlines()
    if not out:
        return
    print(f"\n--- diff for {rel} (truncated to {max_lines} lines) ---")
    for line in out[:max_lines]:
        print(line)
    if len(out) > max_lines:
        print(f"... ({len(out) - max_lines} more lines)")


def main(argv: Iterable[str]) -> int:
    args = parse_args(argv)

    if args.check:
        committed = args.output.resolve()
        if not committed.is_dir():
            raise SystemExit(
                f"--check requires the committed output at {committed} to exist."
            )
        # Build into a scratch directory under STAGING_ROOT so we can diff
        # against the committed tree without touching it.
        _wipe(CHECK_OUTPUT)
        CHECK_OUTPUT.mkdir(parents=True)
        # Copy preserved files into the scratch output so the diff ignores
        # them (otherwise they would show up as "only in committed output").
        for name in PRESERVED_PATHS:
            src = committed / name
            if src.is_file():
                shutil.copy2(src, CHECK_OUTPUT / name)
            elif src.is_dir():
                shutil.copytree(src, CHECK_OUTPUT / name)

        build(CHECK_OUTPUT)

        diffs = _diff_trees(committed, CHECK_OUTPUT)
        if not diffs:
            if not args.keep_staging:
                _wipe(STAGING_ROOT)
            print(f"OK: {committed} matches the output of the build pipeline.")
            return 0

        print(
            f"\nERROR: {committed} is out of sync with the build pipeline.\n"
            "Run `make docs-python-client` (or `python3 scripts/"
            "build_api_client_python_docs.py`) and commit the result.\n"
            "\nSummary of differences:"
        )
        for line in diffs:
            print(line)
        # Show a unified diff for the first few mismatched text files so
        # CI logs make the cause obvious.
        text_mismatches = [
            d.split(": ", 1)[1] for d in diffs if d.lstrip().startswith("differs:")
        ]
        for rel in text_mismatches[:3]:
            if rel.endswith((".md", ".yaml", ".txt")):
                _show_text_diff(committed, CHECK_OUTPUT, rel)
        return 1

    build(args.output)

    if not args.keep_staging:
        _wipe(STAGING_ROOT)

    print(f"Done. Output at {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
