#!/usr/bin/env python3
"""Build the api-client-python GitBook space.

This orchestrator wraps Sphinx so that the MyST-Markdown + RST sources in
``submodules/api-client-python/docs/source`` are rendered to GitBook-native
Markdown under ``spaces/api-client-python/docs``.

Every file under ``spaces/api-client-python/docs`` (except the static
``.gitbook.yaml``) is regenerated by this script:

* ``SUMMARY.md`` is composed from ``SUMMARY_CONFIG`` so the sidebar always
  matches the set of pages the build emits.
* The page tree under ``reference/``, ``user-guide/`` and ``releases/`` is
  produced by Sphinx + sphinx-apidoc + the upstream ``_generate_groups.py``.
* ``.gitbook/assets/`` is wiped and re-populated from the submodule's
  ``_static/images/`` directory.

This means a full rebuild is byte-for-byte reproducible from the submodule
SHA pinned in ``submodules/api-client-python``: running
``scripts/build_api_client_python_docs.py --check`` re-runs the whole
pipeline into a scratch directory and exits non-zero if anything differs
from what is committed under ``spaces/api-client-python/docs``.

The pipeline itself works as follows. It deliberately leaves the submodule
untouched and instead:

1. Stages the submodule's ``docs/source`` tree into ``.docs-build/source``.
2. Runs the submodule's ``_generate_groups.py`` to (re)create the per-endpoint
   reference pages, with its module-level ``REPO_ROOT`` and ``OUTPUT_DIR``
   monkey-patched to the staged paths so nothing is written into the submodule
   working tree.
3. Drops in an overlay ``conf.py`` that re-exports the submodule conf and
   appends ``sphinx_markdown_builder`` to ``extensions``.
4. Invokes ``sphinx-build -b markdown`` against the staged source.
5. Post-processes the generated Markdown:
   - rewrites ``.html`` links to ``.md``
   - strips residual ``{toctree}`` and ``{eval-rst}`` fences
   - converts ``{grid-item-card}`` blocks to GitBook-friendly bullet lists
   - rewrites ``_static/images/...`` references to ``.gitbook/assets/...``
   - copies image assets into ``<output>/.gitbook/assets``
6. Writes ``<output>/SUMMARY.md`` from ``SUMMARY_CONFIG``.
"""

from __future__ import annotations

import argparse
import filecmp
import importlib.util
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable, List, Optional, Tuple


REPO_ROOT = Path(__file__).resolve().parents[1]
SUBMODULE_ROOT = REPO_ROOT / "submodules" / "api-client-python"
SUBMODULE_DOCS_SOURCE = SUBMODULE_ROOT / "docs" / "source"
SUBMODULE_CHANGELOG = SUBMODULE_ROOT / "CHANGELOG.md"

STAGING_ROOT = REPO_ROOT / ".docs-build" / "api-client-python"
STAGED_SOURCE = STAGING_ROOT / "source"
STAGED_BUILD = STAGING_ROOT / "build"
CHECK_OUTPUT = STAGING_ROOT / "check-output"

DEFAULT_OUTPUT_ROOT = REPO_ROOT / "spaces" / "api-client-python" / "docs"
GITBOOK_ASSETS_REL = Path(".gitbook") / "assets"

# Files in the output root that are committed by hand and must survive a
# clean rebuild. Everything else under the output root (including
# SUMMARY.md and .gitbook/assets/) is owned by this script.
PRESERVED_PATHS = {
    ".gitbook.yaml",
}

GROUP_PAGES = [
    ("catalog-v2", "Catalog v2"),
    ("timeseries", "Time Series"),
    ("reference-data", "Reference Data"),
    ("security-master", "Security Master"),
    ("taxonomy", "Taxonomy"),
    ("asset-profiles", "Asset Profiles"),
    ("constituents", "Constituents"),
    ("blockchain-data", "Blockchain Data"),
    ("blockchain-metadata", "Blockchain Metadata"),
]

# Source-relative path -> output-relative path. Pages not listed are emitted
# at the same relative location (with name normalisation underscore->dash).
PAGE_RENAMES = {
    "index.md": "README.md",
    "user-guide/index.md": "user-guide/README.md",
    "reference/api_client.md": "reference/README.md",
    "reference/coinmetricsclient.md": "reference/coinmetricsclient.md",
    "reference/cm_stream.md": "reference/cm-stream.md",
    # The curated upstream pages are kept for DataCollection and
    # ParallelDataCollection because each class deserves a dedicated page in
    # the GitBook sidebar (sphinx-apidoc would otherwise dump both into a
    # single ``coinmetrics._data_collection`` module page).
    "reference/data_collection.md": "reference/data-collection.md",
    "reference/parallel_data_collection.md": "reference/parallel-data-collection.md",
    # The exceptions page is produced by sphinx-apidoc against the actual
    # Python package (see _run_apidoc) so every exception class is picked
    # up automatically.
    "reference/coinmetrics._exceptions.md": "reference/exceptions.md",
    "releases/changelog.md": "releases/changelog.md",
}

# Generated group pages are nested under reference/coinmetricsclient/.
for slug, _label in GROUP_PAGES:
    PAGE_RENAMES[f"reference/groups/{slug}.md"] = f"reference/coinmetricsclient/{slug}.md"

# Output-relative path -> H1 title. Used by post-processing to replace the
# default ``coinmetrics.<module> module`` heading sphinx-apidoc emits with a
# friendlier label that matches the upstream curated pages.
PAGE_TITLES = {
    "reference/exceptions.md": "Exceptions",
}

# Default class qualifier used to resolve "plain" autodoc method headings
# (the ones rendered as ``ClassName.method(...)`` without a module prefix,
# typically emitted by ``.. automethod::`` under a ``.. currentmodule::``
# directive). The qualifier is the fully-qualified class name; method
# anchors are built as ``<qualifier>.<method>``.
#
# Pages without an entry rely on the most-recent ``*class*`` / ``*exception*``
# heading on the page to set the qualifier dynamically.
PAGE_DEFAULT_CLASS_QUALIFIER = {
    # Group pages live under reference/coinmetricsclient/ and only contain
    # methods of CoinMetricsClient (no class heading).
    "reference/coinmetricsclient/": "coinmetrics.api_client.CoinMetricsClient",
    # The CmStream page renders ``run`` etc. without the class prefix.
    "reference/cm-stream.md": "coinmetrics.api_client.CmStream",
}

# Curated upstream reference pages we discard during staging because their
# content is now produced from the actual Python package by sphinx-apidoc.
# DataCollection / ParallelDataCollection stay curated so each class keeps
# its own dedicated GitBook sidebar entry.
DROP_FROM_STAGED_REFERENCE = (
    "exceptions.md",
)

# Modules under coinmetrics/ that sphinx-apidoc should NOT document. We
# keep ``api_client.py`` curated (because the per-endpoint groupings under
# reference/coinmetricsclient/ are far easier to navigate than a single
# automodule dump), keep ``_data_collection.py`` curated (so DataCollection
# and ParallelDataCollection get their own pages), drop ``constants.py``
# because the constants are referenced inline in the relevant prose pages,
# and ignore implementation-detail modules that have no user-facing surface.
APIDOC_EXCLUDE_FILES = (
    "api_client.py",
    "constants.py",
    "_catalogs.py",
    "_data_collection.py",
    "_models.py",
    "_schema.py",
    "_schema_base.py",
    "_schema_gen.py",
    "_typing.py",
    "_utils.py",
)


# ---------------------------------------------------------------------------
# SUMMARY.md generation
# ---------------------------------------------------------------------------


# Declarative GitBook navigation. Each section is a (heading_or_None, entries)
# pair, where ``entries`` is an ordered list of ``(title, target, children)``
# triples. ``target`` is the link target relative to the GitBook space root.
# ``children`` is itself a list of ``(title, target, [])`` triples (only one
# nesting level is supported, which matches the upstream pydata layout).
#
# The CoinMetricsClient entry's children are filled in from ``GROUP_PAGES``
# at render time so the sidebar always lists every group page the build
# emits under ``reference/coinmetricsclient/``.
SUMMARY_INTRO = ("Introduction", "../../")

SUMMARY_CONFIG: List[Tuple[str | None, List[Tuple[str, str, List[Tuple[str, str]]]]]] = [
    (
        "User Guide",
        [
            ("Overview", "user-guide/", []),
            ("Core Concepts", "user-guide/core-concepts.md", []),
            ("Best Practices", "user-guide/best-practices.md", []),
            ("Troubleshooting", "user-guide/troubleshooting.md", []),
        ],
    ),
    (
        "Reference",
        [
            ("Overview", "reference/", []),
            (
                "CoinMetricsClient",
                "reference/coinmetricsclient.md",
                # Filled in at render time from GROUP_PAGES.
                [],
            ),
            ("Data Collection", "reference/data-collection.md", []),
            ("Parallel Data Collection", "reference/parallel-data-collection.md", []),
            ("CmStream", "reference/cm-stream.md", []),
            ("Exceptions", "reference/exceptions.md", []),
        ],
    ),
    (
        "RELEASES",
        [
            ("Changelog", "releases/changelog.md", []),
        ],
    ),
]


def _render_summary() -> str:
    """Compose ``SUMMARY.md`` from ``SUMMARY_CONFIG`` and ``GROUP_PAGES``.

    Per-method entries are intentionally NOT emitted: GitBook collapses
    deeply nested SUMMARY entries by default (so they would not be visible
    anyway) and inflates the sidebar for every page. Method-level
    discoverability is handled by GitBook's full-text search, which indexes
    the qualified ``ClassName.method`` headings rendered on each page.
    """
    lines: List[str] = ["# Table of contents", ""]
    intro_title, intro_target = SUMMARY_INTRO
    lines.append(f"* [{intro_title}]({intro_target})")
    lines.append("")
    for heading, entries in SUMMARY_CONFIG:
        if heading is not None:
            lines.append(f"## {heading}")
            lines.append("")
        for title, target, children in entries:
            lines.append(f"* [{title}]({target})")
            # Inject the auto-discovered per-endpoint group pages beneath
            # CoinMetricsClient.
            if target == "reference/coinmetricsclient.md":
                for slug, label in GROUP_PAGES:
                    page = f"reference/coinmetricsclient/{slug}.md"
                    lines.append(f"  * [{label}]({page})")
            for child_title, child_target in children:
                lines.append(f"  * [{child_title}]({child_target})")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_summary(output_root: Path) -> None:
    """Write the rendered ``SUMMARY.md`` into ``output_root``."""
    (output_root / "SUMMARY.md").write_text(_render_summary())


# ---------------------------------------------------------------------------
# Staging
# ---------------------------------------------------------------------------


def _wipe(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)


def stage_source() -> None:
    """Copy the submodule docs source into the staging root."""
    if not SUBMODULE_DOCS_SOURCE.is_dir():
        raise SystemExit(
            f"Cannot find submodule docs source at {SUBMODULE_DOCS_SOURCE}. "
            "Did you run `git submodule update --init --recursive`?"
        )
    _wipe(STAGING_ROOT)
    STAGING_ROOT.mkdir(parents=True)
    shutil.copytree(SUBMODULE_DOCS_SOURCE, STAGED_SOURCE)

    # Bring in the CHANGELOG so the toctree entry "releases/CHANGELOG"
    # resolves. The Sphinx myst-parser does not need a file extension on
    # toctree references, so we expose the changelog at releases/changelog.md
    # and patch the toctree below.
    releases_dir = STAGED_SOURCE / "releases"
    releases_dir.mkdir(exist_ok=True)
    if SUBMODULE_CHANGELOG.is_file():
        shutil.copy2(SUBMODULE_CHANGELOG, releases_dir / "changelog.md")

    _patch_index_toctree(STAGED_SOURCE / "index.md")
    _drop_curated_reference_pages(STAGED_SOURCE / "reference")
    _run_apidoc(SUBMODULE_ROOT / "coinmetrics", STAGED_SOURCE / "reference")
    _strip_grids_in_tree(STAGED_SOURCE)
    _strip_toctrees_in_tree(STAGED_SOURCE)
    _convert_admonitions_in_tree(STAGED_SOURCE)
    _write_overlay_conf(STAGED_SOURCE / "conf.py")


def _drop_curated_reference_pages(reference_dir: Path) -> None:
    """Remove staged curated pages that sphinx-apidoc will replace."""
    for name in DROP_FROM_STAGED_REFERENCE:
        target = reference_dir / name
        if target.exists():
            target.unlink()


def _run_apidoc(package_dir: Path, output_dir: Path) -> None:
    """Run ``sphinx-apidoc`` to scaffold per-module reference pages.

    The generated ``coinmetrics.<module>.rst`` files use the standard
    ``automodule :members: :undoc-members: :show-inheritance:`` template
    that produces the canonical Sphinx API-reference look.

    Two upstream knobs need taming:

    * ``-P`` (private) is required so ``coinmetrics._data_collection`` and
      ``coinmetrics._exceptions`` (both underscore-prefixed at the module
      level) are emitted, but it also injects ``:private-members:`` into
      every directive. We strip that line so single-leading-underscore
      *attributes* inside the modules stay hidden.
    * ``-T`` skips the ``modules.rst`` table-of-contents file (we drive
      navigation from SUMMARY.md instead). We also remove the package-level
      ``coinmetrics.rst`` for the same reason.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    excludes = [str(package_dir / name) for name in APIDOC_EXCLUDE_FILES]
    cmd = [
        sys.executable,
        "-m",
        "sphinx.ext.apidoc",
        "-e",      # one file per module
        "-M",      # module docs above submodule entries
        "-T",      # do not emit the modules.rst TOC
        "-P",      # include underscore-prefixed modules
        "-f",      # overwrite existing files
        "-o",
        str(output_dir),
        str(package_dir),
        *excludes,
    ]
    print("$ " + " ".join(cmd))
    result = subprocess.run(cmd, cwd=str(REPO_ROOT))
    if result.returncode != 0:
        # Older sphinx releases ship apidoc only as a console script rather
        # than as a runnable module; fall back to the CLI before giving up.
        result = subprocess.run(
            ["sphinx-apidoc", *cmd[3:]],
            cwd=str(REPO_ROOT),
        )
        if result.returncode != 0:
            raise SystemExit(f"sphinx-apidoc exited with {result.returncode}")

    # Drop the package-level "coinmetrics" landing page; SUMMARY.md provides
    # navigation, and the page would otherwise emit an empty automodule
    # block plus a redundant submodule toctree.
    package_index = output_dir / f"{package_dir.name}.rst"
    if package_index.exists():
        package_index.unlink()

    # Strip ``:private-members:`` from every generated directive so we only
    # document the public surface of each module.
    for rst in output_dir.glob(f"{package_dir.name}.*.rst"):
        text = rst.read_text()
        text = re.sub(r"^\s*:private-members:\s*\n", "", text, flags=re.MULTILINE)
        rst.write_text(text)


def _patch_index_toctree(index_path: Path) -> None:
    """Point the landing toctree at the staged ``releases/changelog`` page."""
    text = index_path.read_text()
    text = text.replace("releases/CHANGELOG", "releases/changelog")
    index_path.write_text(text)


# Matches a sphinx-design ``::::{grid}`` block (4 colons) wrapping one or
# more ``:::{grid-item-card}`` (3 colons) entries. The grid is rendered by
# pydata-sphinx-theme as visual landing cards, but in GitBook it would just
# duplicate the navigation already shown in the left sidebar (see
# SUMMARY.md), so we drop the entire block at the source-text level before
# Sphinx parses it.
_GRID_BLOCK_RE = re.compile(
    r"\n?^::::\{grid\}[^\n]*\n.*?^::::\s*$",
    re.DOTALL | re.MULTILINE,
)


def _strip_grids_in_tree(root: Path) -> None:
    """Remove every ``{grid}`` block from Markdown files under ``root``."""
    for md in root.rglob("*.md"):
        text = md.read_text()
        new_text = _GRID_BLOCK_RE.sub("", text)
        if new_text != text:
            md.write_text(new_text)


# Matches a MyST ``{toctree}`` directive. ``sphinx_markdown_builder`` lowers
# these to bullet lists in the rendered output, which duplicates the GitBook
# left sidebar driven by SUMMARY.md. Strip them at the source so the
# rendered pages stay focused on prose + autodoc reference content.
_TOCTREE_BLOCK_RE = re.compile(
    r"\n?^```\{toctree\}.*?^```\s*$",
    re.DOTALL | re.MULTILINE,
)


def _strip_toctrees_in_tree(root: Path) -> None:
    """Remove every ``{toctree}`` block from Markdown files under ``root``."""
    for md in root.rglob("*.md"):
        text = md.read_text()
        new_text = _TOCTREE_BLOCK_RE.sub("", text)
        if new_text != text:
            md.write_text(new_text)


# After stripping grid and toctree blocks, some pages are left with section
# headings (``## Explore the Docs``) that no longer have any body. Remove
# such empty sections so they do not show up as blank entries in the
# rendered output.
#
# The match is intentionally restrictive: we only strip a heading whose body
# is empty *and* whose next heading is at the same or shallower level. That
# preserves the common pattern of an H2 that introduces a group of H3s
# without any prose of its own (e.g. the ``## Transport and client errors``
# header in reference/exceptions.md).
_HEADING_RE = re.compile(r"^(?P<hashes>#{1,6})\s+([^\n]+)$", re.MULTILINE)


def _strip_empty_sections(text: str) -> str:
    while True:
        headings = list(_HEADING_RE.finditer(text))
        if not headings:
            return text
        removed = False
        for idx, match in enumerate(headings):
            level = len(match.group("hashes"))
            if level < 2:
                continue
            body_start = match.end() + 1  # skip newline after heading
            if idx + 1 < len(headings):
                next_match = headings[idx + 1]
                next_level = len(next_match.group("hashes"))
                body = text[body_start:next_match.start()]
            else:
                next_level = 0  # treat EOF as "shallower" so trailing
                                # empty sections are also stripped
                body = text[body_start:]
            if next_level > level:
                # The next heading is a child of this one, so this heading
                # is acting as a section label even if it has no prose.
                continue
            if body.strip():
                continue
            # Strip the heading line and the blank lines that follow.
            text = text[: match.start()] + text[
                next_match.start() if idx + 1 < len(headings) else len(text):
            ]
            removed = True
            break
        if not removed:
            return text


# MyST admonition directives -> GitBook hint blocks. ``sphinx_markdown_builder``
# silently drops most admonitions ("unknown node type: <tip: ...>"), so we
# convert them to GitBook's native ``{% hint %}`` markup before Sphinx sees
# them. The mapping covers the standard MyST directives that share semantics
# with GitBook's four hint styles.
_ADMONITION_STYLES = {
    "tip": "info",
    "note": "info",
    "hint": "info",
    "important": "info",
    "attention": "warning",
    "caution": "warning",
    "warning": "warning",
    "danger": "danger",
    "error": "danger",
    "seealso": "info",
}
_ADMONITION_RE = re.compile(
    r"^```\{(?P<kind>"
    + "|".join(_ADMONITION_STYLES.keys())
    + r")\}\s*\n(?P<body>.*?)^```\s*$",
    re.DOTALL | re.MULTILINE,
)


def _convert_admonition(match: re.Match[str]) -> str:
    style = _ADMONITION_STYLES[match.group("kind")]
    body = match.group("body").rstrip()
    return f'{{% hint style="{style}" %}}\n{body}\n{{% endhint %}}'


def _convert_admonitions_in_tree(root: Path) -> None:
    """Apply ``_convert_admonition`` to every Markdown file under ``root``."""
    for md in root.rglob("*.md"):
        text = md.read_text()
        new_text = _ADMONITION_RE.sub(_convert_admonition, text)
        if new_text != text:
            md.write_text(new_text)


def _write_overlay_conf(conf_path: Path) -> None:
    """Replace the staged conf.py with an overlay that adds the markdown builder.

    ``sys.path`` is set up so the staged conf can still import the submodule's
    Python package for autodoc. We also disable the ``primary_sidebar_end``
    HTML-only option, which is harmless under the markdown builder but emits
    a warning.
    """
    overlay_template = '''"""Overlay Sphinx configuration for the GitBook markdown build.

This file is generated by scripts/build_api_client_python_docs.py. It re-uses
the upstream configuration from the api-client-python submodule and only adds
``sphinx_markdown_builder`` so the same source tree can be rendered as
GitBook-friendly Markdown.
"""

from __future__ import annotations

import os
import sys

SUBMODULE_SOURCE = __SUBMODULE_SOURCE__
SUBMODULE_ROOT = __SUBMODULE_ROOT__

# Allow autodoc to import the coinmetrics package directly from the submodule.
sys.path.insert(0, SUBMODULE_ROOT)
sys.path.insert(0, SUBMODULE_SOURCE)

# Re-export the upstream Sphinx config (project, extensions, autodoc options,
# myst extensions, intersphinx mappings, ...).
from conf import *  # noqa: F401,F403,E402

# The markdown builder is additive: it consumes the same parsed doctree the
# HTML builder would, including autodoc / sphinx-design / eval-rst output.
extensions = list(globals().get("extensions", []))
if "sphinx_markdown_builder" not in extensions:
    extensions.append("sphinx_markdown_builder")

# Belt-and-suspenders: the HTML theme options carry pydata-sphinx-theme keys
# that the markdown builder does not understand. Keep them but make the
# fallback explicit.
html_theme = globals().get("html_theme", "alabaster")

# Suppress noisy "toctree contains reference to nonexisting document"
# warnings for upstream pages we have not staged (e.g. examples.md).
suppress_warnings = list(globals().get("suppress_warnings", []))
for code in ("toc.not_included", "myst.xref_missing", "ref.doc", "toc.excluded"):
    if code not in suppress_warnings:
        suppress_warnings.append(code)

# GitBook hint blocks use ASCII double quotes inside ``{%% hint style="info" %%}``,
# so disable Sphinx's smart-quote transform that would otherwise rewrite them
# to curly Unicode quotes.
smartquotes = False
'''
    overlay = (
        overlay_template
        .replace("__SUBMODULE_SOURCE__", repr(str(SUBMODULE_DOCS_SOURCE)))
        .replace("__SUBMODULE_ROOT__", repr(str(SUBMODULE_ROOT)))
    )
    conf_path.write_text(overlay)


# ---------------------------------------------------------------------------
# Group page generation
# ---------------------------------------------------------------------------


def regenerate_group_pages() -> None:
    """Run the upstream ``_generate_groups.py`` against the staged tree.

    The upstream script writes RST files to its own ``groups`` directory and
    derives ``REPO_ROOT`` from ``__file__``. We import it as a module and
    overwrite both module-level constants so it operates on the staged tree
    without touching the submodule.
    """
    src = STAGED_SOURCE / "reference" / "_generate_groups.py"
    if not src.is_file():
        raise SystemExit(f"Missing {src}; staging step did not complete.")

    spec = importlib.util.spec_from_file_location("_acp_generate_groups", src)
    if spec is None or spec.loader is None:
        raise SystemExit(f"Could not load {src}")
    module = importlib.util.module_from_spec(spec)
    # ``@dataclass`` looks up ``cls.__module__`` in ``sys.modules`` while
    # processing the class body, so the module must be registered before
    # exec_module runs.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)

    # Override the upstream constants so the script reads from the real
    # submodule and writes into the staged source tree.
    module.REPO_ROOT = SUBMODULE_ROOT
    module.API_CLIENT_PATH = SUBMODULE_ROOT / "coinmetrics" / "api_client.py"
    module.OUTPUT_DIR = STAGED_SOURCE / "reference" / "groups"

    # Replace the upstream group renderer with one that skips the
    # ``.. autosummary::`` table at the top. The autosummary table is a
    # condensed TOC of every method on the page and duplicates both the
    # GitBook right-hand anchor list and the per-method headings emitted
    # below it by ``.. automethod::``. Dropping it keeps the page focused on
    # the actual reference content.
    class_name = module.CLASS_NAME

    def _render_group_no_autosummary(group) -> str:  # type: ignore[no-untyped-def]
        underline = "=" * len(group.label)
        header = (
            f"{group.label}\n{underline}\n\n"
            f".. currentmodule:: coinmetrics.api_client\n\n"
        )
        auto_methods = "\n".join(
            f".. automethod:: {class_name}.{name}" for name in group.methods
        )
        return header + auto_methods + "\n"

    module._render_group = _render_group_no_autosummary
    module.main()


# ---------------------------------------------------------------------------
# Sphinx build
# ---------------------------------------------------------------------------


def run_sphinx() -> None:
    _wipe(STAGED_BUILD)
    STAGED_BUILD.mkdir(parents=True)
    cmd = [
        sys.executable,
        "-m",
        "sphinx",
        "-b",
        "markdown",
        "-q",
        str(STAGED_SOURCE),
        str(STAGED_BUILD),
    ]
    print("$ " + " ".join(cmd))
    result = subprocess.run(cmd, cwd=str(REPO_ROOT))
    if result.returncode != 0:
        raise SystemExit(f"sphinx-build exited with {result.returncode}")


# ---------------------------------------------------------------------------
# Output assembly
# ---------------------------------------------------------------------------


def reset_output(output_root: Path) -> None:
    """Wipe ``output_root`` so the build starts from a known clean state.

    Only ``PRESERVED_PATHS`` survive (``.gitbook.yaml`` is kept because it
    pins the GitBook space configuration and is not produced by the build).
    Everything else, including ``SUMMARY.md`` and ``.gitbook/assets/``, is
    removed up front so a previous run cannot leave stale files behind.
    """
    if not output_root.exists():
        output_root.mkdir(parents=True)
        return
    for entry in output_root.iterdir():
        if entry.name in PRESERVED_PATHS:
            continue
        if entry.is_dir():
            shutil.rmtree(entry)
        else:
            entry.unlink()


def collect_outputs(output_root: Path) -> None:
    """Move/rename generated Markdown files into ``output_root``."""
    if not STAGED_BUILD.is_dir():
        raise SystemExit(f"Sphinx build directory missing: {STAGED_BUILD}")

    for src in STAGED_BUILD.rglob("*.md"):
        rel = src.relative_to(STAGED_BUILD).as_posix()
        target_rel = PAGE_RENAMES.get(rel)
        if target_rel is None:
            target_rel = rel.replace("_", "-")
            # Drop the staged "groups/" subdirectory if it leaks through.
            if target_rel.startswith("reference/groups/"):
                target_rel = target_rel.replace(
                    "reference/groups/", "reference/coinmetricsclient/", 1
                )
        target = output_root / target_rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, target)


def copy_assets(output_root: Path) -> None:
    """Mirror static images into the GitBook assets folder.

    The assets directory is wiped first so images removed upstream do not
    linger in the committed output.
    """
    src_dir = SUBMODULE_DOCS_SOURCE / "_static" / "images"
    assets_dir = output_root / GITBOOK_ASSETS_REL
    if assets_dir.exists():
        shutil.rmtree(assets_dir)
    if not src_dir.is_dir():
        return
    assets_dir.mkdir(parents=True, exist_ok=True)
    for image in src_dir.iterdir():
        if image.is_file():
            shutil.copy2(image, assets_dir / image.name)


# ---------------------------------------------------------------------------
# Post-processing
# ---------------------------------------------------------------------------


_RESIDUAL_TOCTREE_RE = re.compile(
    r"^```\{toctree\}.*?^```\s*$",
    re.DOTALL | re.MULTILINE,
)
_RESIDUAL_EVAL_RST_RE = re.compile(
    r"^```\{eval-rst\}.*?^```\s*$",
    re.DOTALL | re.MULTILINE,
)
_STATIC_IMAGE_RE = re.compile(r"_static/images/")

# ``sphinx_markdown_builder`` rewrites every cross-reference to use a ``.md``
# extension, including the intersphinx links that resolve to external HTML
# documentation. Detect and fix the external ones.
_INTERSPHINX_HOSTS = (
    "docs.python.org",
    "pandas.pydata.org",
    "numpy.org",
)
_INTERSPHINX_RE = re.compile(
    r"(\]\(https?://(?:" + "|".join(re.escape(h) for h in _INTERSPHINX_HOSTS) + r")[^)\s]*?)\.md(?=[)#])"
)

# Autodoc rendering. ``sphinx-markdown-builder`` emits headings like
#
#     ### *class* coinmetrics.api_client.CoinMetricsClient(api_key='', ...)
#     #### CoinMetricsClient.get_asset_metrics(assets, ...)
#     #### *property* CoinMetricsClient.foo
#
# These have two problems for GitBook:
#
# 1. The full signature ends up in the heading text. GitBook's right-hand
#    "On this page" panel shows headings as anchor links, so a 200-character
#    constructor signature is unusable as navigation.
# 2. Sphinx's intra-doc cross-references resolve to anchors named after the
#    fully-qualified Python path (``coinmetrics.api_client.CoinMetricsClient``),
#    but GitBook slugifies headings into something completely different, so
#    every ``[Foo](page.md#coinmetrics.x.Foo)`` link is silently broken.
#
# We rewrite each autodoc heading into:
#
#     <a id="coinmetrics.api_client.CoinMetricsClient"></a>
#
#     ### *class* CoinMetricsClient
#
#     ```python
#     class coinmetrics.api_client.CoinMetricsClient(
#         api_key='',
#         verify_ssl_certs=True,
#         ...
#     )
#     ```
#
# which gives GitBook a clean short heading, a stable anchor that matches
# Sphinx's cross-link IDs, and the full pydata-style signature underneath.
#
# Method headings (``#### CoinMetricsClient.foo``) are also promoted to H3
# so they appear in GitBook's "On this page" right-hand panel.

# Kinds where the heading payload contains the FULLY-QUALIFIED dotted path
# (sphinx-markdown-builder always emits class/exception/function with the
# module prefix, regardless of ``.. currentmodule::``).
_QUALIFIED_KINDS = frozenset({"class", "exception", "function", "data"})
_AUTODOC_KIND_RE = re.compile(
    r"^(?P<hashes>#{2,5})\s+"
    r"\*(?P<kind>class|exception|function|method|staticmethod|classmethod|"
    r"abstractmethod|property|attribute|data)\*\s+"
    r"(?P<rest>\S.*?)\s*$"
)
# Plain method/function headings without an explicit kind label, e.g.
# ``#### CoinMetricsClient.get_asset_metrics(...)`` or ``#### run(...)``.
# Match identifiers (with optional dotted path) followed by an optional
# parenthesised argument list, but NOT bare prose headings like
# ``## Endpoints``.
_AUTODOC_PLAIN_RE = re.compile(
    r"^(?P<hashes>#{2,5})\s+"
    r"(?P<rest>"
    r"[A-Za-z_]\w*(?:\\?\.[\w\\]+)+(?:\([^\n]*\))?"  # dotted name (+optional args)
    r"|[A-Za-z_]\w*\([^\n]*\)"                        # bare name + args
    r")\s*$"
)


def _unescape_sig(sig: str) -> str:
    """Drop the ``\\*`` / ``\\_`` escapes the markdown builder injects.

    These escapes are needed in plain Markdown so ``**kwargs`` does not
    render as bold, but inside a code block they would render literally.
    """
    return sig.replace("\\*", "*").replace("\\_", "_")


def _split_signature(payload: str) -> Tuple[str, Optional[str]]:
    """Split ``Foo.bar(arg=1, arg2)`` into ``("Foo.bar", "arg=1, arg2")``.

    Returns ``(dotted_name, None)`` if the payload has no parenthesised
    argument list (e.g. property / attribute signatures).
    """
    payload = payload.strip()
    if "(" not in payload:
        return payload, None
    # Match the FIRST opening parenthesis and take everything to the matching
    # closing one. The args may themselves contain balanced parens (default
    # values like ``factory()``); walk the string to find the right close.
    open_idx = payload.index("(")
    depth = 0
    for i, ch in enumerate(payload[open_idx:], start=open_idx):
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return payload[:open_idx], payload[open_idx + 1 : i]
    # Unbalanced -- fall back to a simple split.
    return payload[:open_idx], payload[open_idx + 1 :].rstrip(") ")


def _format_signature_block(prefix: str, full_dotted: str, args: Optional[str]) -> str:
    """Render the ``python``-fenced signature block printed under each heading."""
    head = f"{prefix} {full_dotted}".strip()
    if args is None:
        body = head
    else:
        # Split args on top-level commas (so ``Dict[str, int]`` stays intact)
        # and put each on its own line for readability.
        pieces: List[str] = []
        depth = 0
        current = ""
        for ch in args:
            if ch in "([{":
                depth += 1
            elif ch in ")]}":
                depth -= 1
            if ch == "," and depth == 0:
                pieces.append(current.strip())
                current = ""
            else:
                current += ch
        if current.strip():
            pieces.append(current.strip())
        if len(pieces) <= 1 or sum(len(p) for p in pieces) + len(head) < 80:
            body = f"{head}({args.strip()})"
        else:
            body = head + "(\n    " + ",\n    ".join(pieces) + ",\n)"
    return "```python\n" + body + "\n```"


def _emit_autodoc_heading(
    hashes: str,
    kind: Optional[str],
    display_name: str,
    anchor: str,
    full_dotted: str,
    args: Optional[str],
    promote_to_h3: bool,
) -> List[str]:
    """Build the multi-line replacement for a single autodoc heading.

    ``display_name`` is the human-readable text rendered inside the heading
    itself. For class / exception / function it is the short symbol name
    (``CoinMetricsClient``). For method / property / attribute headings it
    is the qualified ``ClassName.symbol`` form -- this matches Sphinx's
    native pydata rendering and, more importantly for GitBook, makes every
    method heading globally unique so it ranks well in the search bar.
    """
    level = "###" if promote_to_h3 and len(hashes) > 3 else hashes
    label = f"{level} *{kind}* {display_name}" if kind else f"{level} {display_name}"
    if kind in {"class", "exception"}:
        prefix = kind
    elif kind == "function":
        prefix = "def"
    elif kind in {"method", "staticmethod", "classmethod", "abstractmethod"}:
        prefix = "def"
    else:
        prefix = ""
    return [
        f'<a id="{anchor}"></a>',
        "",
        label,
        "",
        _format_signature_block(prefix, full_dotted, args),
    ]


def _resolve_anchor(
    dotted: str,
    kind: Optional[str],
    class_qualifier: Optional[str],
    module_qualifier: Optional[str],
) -> Tuple[str, str]:
    """Figure out the anchor ID and full dotted path for a heading.

    Returns ``(anchor, full_dotted)``.

    * For class/exception/function/data kinds, the heading payload already
      includes the fully-qualified module path; we use it as-is.
    * For method/property/attribute headings on a documented class, the
      payload may be ``Class.method`` (when emitted under a
      ``currentmodule`` directive) or just ``method`` (when emitted by
      ``automethod`` against a class set as the current context). We
      prepend the module qualifier and the class name as needed.
    """
    if kind in _QUALIFIED_KINDS or "coinmetrics" in dotted:
        return dotted, dotted

    parts = dotted.split(".")
    if class_qualifier:
        # ``class_qualifier`` is itself fully qualified (e.g.
        # ``coinmetrics.api_client.CoinMetricsClient``).
        class_short = class_qualifier.rsplit(".", 1)[-1]
        if parts[0] == class_short:
            full = class_qualifier.rsplit(".", 1)[0] + "." + ".".join(parts)
        else:
            full = class_qualifier + "." + ".".join(parts)
        return full, full

    if module_qualifier:
        full = module_qualifier + "." + ".".join(parts)
        return full, full

    # No context to qualify with -- use the dotted name verbatim. This will
    # not match Sphinx's cross-link anchors but at least keeps the page
    # rendering correctly.
    return dotted, dotted


def _transform_autodoc_headings(text: str, page_rel: str) -> str:
    """Rewrite every autodoc heading on the page (see module-level comment).

    ``page_rel`` is the output-relative path of the file (e.g.
    ``reference/coinmetricsclient/timeseries.md``). It is used to seed the
    class qualifier on pages where Sphinx does not emit a ``*class*``
    heading (group pages and the cm-stream page).
    """
    # Resolve the per-page default class qualifier. Group pages match by
    # directory prefix; everything else by exact path.
    class_qualifier: Optional[str] = None
    module_qualifier: Optional[str] = None
    for prefix, qualifier in PAGE_DEFAULT_CLASS_QUALIFIER.items():
        if page_rel.startswith(prefix) or page_rel == prefix:
            class_qualifier = qualifier
            module_qualifier = qualifier.rsplit(".", 1)[0]
            break

    # Whether a ``*class*`` / ``*exception*`` heading has appeared on this
    # page. When true, method/property headings stay one Markdown level
    # below the class heading (e.g. class at H3 -> methods at H4) so the
    # rendered TOC visually nests methods under their parent class -- this
    # matches Sphinx's native pydata layout. When false (group pages, which
    # are flat lists of methods under a synthetic ``currentmodule``), method
    # headings are promoted to H3 so they remain top-level on the page and
    # show up in GitBook's right-hand "On this page" panel.
    seen_class_on_page = False

    out: List[str] = []

    def _append_block(block: List[str]) -> None:
        # Ensure a blank line precedes the inline HTML anchor; without it
        # CommonMark may glue the anchor onto the previous heading or
        # paragraph, suppressing the rewritten heading entirely.
        if out and out[-1].strip():
            out.append("")
        out.extend(block)

    def _qualified_method_name(dotted: str) -> str:
        """``Class.method`` form for use as the displayed heading text."""
        short = dotted.rsplit(".", 1)[-1]
        if class_qualifier:
            class_short = class_qualifier.rsplit(".", 1)[-1]
            # Avoid double-prefixing if Sphinx already emitted ``Class.method``.
            if dotted.startswith(class_short + "."):
                return dotted
            return f"{class_short}.{short}"
        return short

    for line in text.split("\n"):
        m = _AUTODOC_KIND_RE.match(line)
        if m:
            hashes = m.group("hashes")
            kind = m.group("kind")
            payload = _unescape_sig(m.group("rest"))
            dotted, args = _split_signature(payload)
            if kind in {"class", "exception"}:
                # Reset the class context for subsequent method headings.
                class_qualifier = dotted
                module_qualifier = dotted.rsplit(".", 1)[0]
                seen_class_on_page = True
                display = dotted.rsplit(".", 1)[-1]
                anchor, full = dotted, dotted
                promote = False
            elif kind == "function":
                # Module-level functions stay as their short name; they have
                # no enclosing class to qualify with.
                display = dotted.rsplit(".", 1)[-1]
                anchor, full = dotted, dotted
                promote = not seen_class_on_page
            else:
                anchor, full = _resolve_anchor(
                    dotted, kind, class_qualifier, module_qualifier
                )
                display = _qualified_method_name(dotted)
                promote = not seen_class_on_page
            _append_block(
                _emit_autodoc_heading(
                    hashes,
                    kind,
                    display_name=display,
                    anchor=anchor,
                    full_dotted=full,
                    args=args,
                    promote_to_h3=promote,
                )
            )
            continue

        m = _AUTODOC_PLAIN_RE.match(line)
        if m:
            hashes = m.group("hashes")
            payload = _unescape_sig(m.group("rest"))
            dotted, args = _split_signature(payload)
            anchor, full = _resolve_anchor(
                dotted, None, class_qualifier, module_qualifier
            )
            _append_block(
                _emit_autodoc_heading(
                    hashes,
                    kind=None,
                    display_name=_qualified_method_name(dotted),
                    anchor=anchor,
                    full_dotted=full,
                    args=args,
                    promote_to_h3=not seen_class_on_page,
                )
            )
            continue

        out.append(line)

    return "\n".join(out)


def post_process_file(path: Path, output_root: Path) -> None:
    text = path.read_text()
    original = text

    # Belt-and-suspenders: ``sphinx_markdown_builder`` consumes ``{toctree}``
    # and ``{eval-rst}`` blocks itself, but if anything slips through (for
    # example because the staged file failed to parse) we strip it here.
    text = _RESIDUAL_TOCTREE_RE.sub("", text)
    text = _RESIDUAL_EVAL_RST_RE.sub("", text)

    # Restore the correct extension on intersphinx URLs the markdown builder
    # mistakenly rewrote to ``.md``.
    text = _INTERSPHINX_RE.sub(r"\1.html", text)

    # The submodule's reference/coinmetricsclient.md toctree points at
    # ``groups/<slug>``. We relocate those generated pages under
    # ``coinmetricsclient/`` so they nest beneath their parent in the GitBook
    # sidebar, so rewrite the parent page's links to match.
    text = re.sub(r"\]\(groups/", "](coinmetricsclient/", text)

    # ``myst-parser`` strips the URL out of links whose target it cannot
    # resolve (e.g. references to documents we have not staged), leaving
    # ``[Label]()``. GitBook would render that as a broken link, so collapse
    # such patterns down to plain text.
    text = re.sub(r"\[([^\]]+)\]\(\)", r"\1", text)

    # The MyST sources reference logos as ``_static/images/...``. The static
    # tree is not copied into the GitBook output, so rewrite to the assets
    # path that GitBook understands. A leading slash makes the reference
    # absolute relative to the space root, which works from any depth.
    text = _STATIC_IMAGE_RE.sub("/.gitbook/assets/", text)

    try:
        rel_to_root = path.relative_to(output_root).as_posix()
    except ValueError:
        rel_to_root = ""

    # Replace the H1 title for sphinx-apidoc-generated pages. The default is
    # ``# coinmetrics.<module> module`` (with backslash-escaped underscores
    # for private modules), which is awkward and exposes the implementation
    # detail of which file a class lives in.
    desired_title = PAGE_TITLES.get(rel_to_root)
    if desired_title is not None:
        text = re.sub(
            r"\A#\s+coinmetrics(?:\\?\.|\.)\\?[\w\\]+\s+module\s*\n",
            f"# {desired_title}\n",
            text,
        )

    # Drop section headings whose body was removed by earlier processing
    # (e.g. ``## Explore the Docs`` after the grid block beneath it was
    # stripped from the source). Done before the autodoc-heading rewrites
    # below so we do not match against a heading that is about to be
    # wrapped in backticks.
    text = _strip_empty_sections(text)

    # Rewrite Sphinx autodoc headings into a GitBook-friendly form: short
    # heading text (just the symbol name), an HTML anchor matching the
    # Sphinx cross-reference ID, and the full signature in a code block.
    # Only apply to the reference tree -- the narrative pages have ordinary
    # headings we should not touch.
    if rel_to_root.startswith("reference/"):
        text = _transform_autodoc_headings(text, rel_to_root)

    # Rewrite intra-doc links that refer to the legacy (underscore or
    # ``index.md``) names of files we have renamed via PAGE_RENAMES.
    # We only need to rewrite the *trailing* portion of the link target so
    # we cover both same-directory references (``data_collection.md``) and
    # parent-relative ones (``reference/api_client.md``).
    #
    # Apply longer source names first so ``parallel_data_collection.md`` is
    # matched before ``data_collection.md`` (which is a suffix of it).
    rename_pairs = sorted(
        PAGE_RENAMES.items(),
        key=lambda item: len(Path(item[0]).name),
        reverse=True,
    )
    for src_rel, target_rel in rename_pairs:
        src_name = Path(src_rel).name
        target_name = Path(target_rel).name
        if src_name == target_name:
            continue
        # Anchor on a ``/`` or ``(`` so we don't slice into longer filenames
        # that happen to end with ``src_name`` (e.g. ``parallel_data_collection``
        # -> ``data_collection``).
        pattern = re.compile(
            r"(\]\((?:[^)#\s]*?[/(])?)" + re.escape(src_name) + r"(?=[)#])"
        )
        text = pattern.sub(lambda m, t=target_name: m.group(1) + t, text)
        # Same-directory bare references like ``](data_collection.md)``.
        text = re.sub(
            r"\]\(" + re.escape(src_name) + r"(?=[)#])",
            f"]({target_name}",
            text,
        )

    if text != original:
        path.write_text(text)


def post_process_outputs(output_root: Path) -> None:
    for md in output_root.rglob("*.md"):
        if md.name == "SUMMARY.md":
            continue
        post_process_file(md, output_root)


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--keep-staging",
        action="store_true",
        help="Do not delete .docs-build after the build (useful for debugging).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT,
        help=(
            "Directory the rendered GitBook space is written to. Defaults to "
            "spaces/api-client-python/docs."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Build into a scratch directory and diff against --output. Exit "
            "non-zero if the committed output is not byte-for-byte identical "
            "to what the pipeline would produce. Used by CI to ensure every "
            "iteration of the GitBook space is reproducible from the script."
        ),
    )
    return parser.parse_args(list(argv))


def build(output_root: Path) -> None:
    """Run the full pipeline, writing the rendered space into ``output_root``."""
    print(f"Staging source from {SUBMODULE_DOCS_SOURCE} -> {STAGED_SOURCE}")
    stage_source()
    print("Regenerating per-endpoint group pages")
    regenerate_group_pages()
    print(f"Running sphinx-build (markdown) -> {STAGED_BUILD}")
    run_sphinx()
    print(f"Resetting {output_root} (preserving {sorted(PRESERVED_PATHS)})")
    reset_output(output_root)
    print("Copying generated Markdown into the GitBook space")
    collect_outputs(output_root)
    print("Copying static image assets")
    copy_assets(output_root)
    print("Post-processing generated Markdown for GitBook")
    post_process_outputs(output_root)
    print("Writing SUMMARY.md")
    write_summary(output_root)


def _diff_trees(expected: Path, actual: Path) -> List[str]:
    """Return a list of human-readable lines describing differences.

    The two trees are compared by file content (not mtime). Files matching
    ``PRESERVED_PATHS`` are skipped because they live outside the build's
    scope. Returns an empty list if the trees are identical.
    """
    diffs: List[str] = []

    def _walk(rel: Path) -> None:
        exp_dir = expected / rel
        act_dir = actual / rel
        cmp = filecmp.dircmp(exp_dir, act_dir)
        for name in sorted(cmp.left_only):
            if rel == Path(".") and name in PRESERVED_PATHS:
                continue
            diffs.append(f"  only in committed output: {(rel / name).as_posix()}")
        for name in sorted(cmp.right_only):
            if rel == Path(".") and name in PRESERVED_PATHS:
                continue
            diffs.append(f"  only in fresh build:       {(rel / name).as_posix()}")
        # ``filecmp.dircmp`` defaults to a shallow comparison (mtime + size);
        # rerun with full content comparison for the candidate matches.
        match, mismatch, errors = filecmp.cmpfiles(
            exp_dir, act_dir, cmp.common_files, shallow=False
        )
        for name in sorted(mismatch + errors):
            if rel == Path(".") and name in PRESERVED_PATHS:
                continue
            diffs.append(f"  differs: {(rel / name).as_posix()}")
        for name in sorted(cmp.common_dirs):
            _walk(rel / name)

    _walk(Path("."))
    return diffs


def _show_text_diff(expected: Path, actual: Path, rel: str, max_lines: int = 60) -> None:
    """Print a unified diff for a single mismatched file (best-effort)."""
    try:
        result = subprocess.run(
            ["diff", "-u", str(expected / rel), str(actual / rel)],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return
    out = result.stdout.splitlines()
    if not out:
        return
    print(f"\n--- diff for {rel} (truncated to {max_lines} lines) ---")
    for line in out[:max_lines]:
        print(line)
    if len(out) > max_lines:
        print(f"... ({len(out) - max_lines} more lines)")


def main(argv: Iterable[str]) -> int:
    args = parse_args(argv)

    if args.check:
        committed = args.output.resolve()
        if not committed.is_dir():
            raise SystemExit(
                f"--check requires the committed output at {committed} to exist."
            )
        # Build into a scratch directory under STAGING_ROOT so we can diff
        # against the committed tree without touching it.
        _wipe(CHECK_OUTPUT)
        CHECK_OUTPUT.mkdir(parents=True)
        # Copy preserved files into the scratch output so the diff ignores
        # them (otherwise they would show up as "only in committed output").
        for name in PRESERVED_PATHS:
            src = committed / name
            if src.is_file():
                shutil.copy2(src, CHECK_OUTPUT / name)
            elif src.is_dir():
                shutil.copytree(src, CHECK_OUTPUT / name)

        build(CHECK_OUTPUT)

        diffs = _diff_trees(committed, CHECK_OUTPUT)
        if not diffs:
            if not args.keep_staging:
                _wipe(STAGING_ROOT)
            print(f"OK: {committed} matches the output of the build pipeline.")
            return 0

        print(
            f"\nERROR: {committed} is out of sync with the build pipeline.\n"
            "Run `make docs-python-client` (or `python3 scripts/"
            "build_api_client_python_docs.py`) and commit the result.\n"
            "\nSummary of differences:"
        )
        for line in diffs:
            print(line)
        # Show a unified diff for the first few mismatched text files so
        # CI logs make the cause obvious.
        text_mismatches = [
            d.split(": ", 1)[1] for d in diffs if d.lstrip().startswith("differs:")
        ]
        for rel in text_mismatches[:3]:
            if rel.endswith((".md", ".yaml", ".txt")):
                _show_text_diff(committed, CHECK_OUTPUT, rel)
        return 1

    build(args.output)

    if not args.keep_staging:
        _wipe(STAGING_ROOT)

    print(f"Done. Output at {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
